### ISSUE TITLE
Question: Use custom Api version selector to match unsupported version to latest down

### ISSUE THREAD

**Issue by sigridbra** [dotnet/aspnet-api-versioning#1003]
Hello! 
I was reading the page about custom [API version selectors](https://github.com/dotnet/aspnet-api-versioning/wiki/API-Version-Selector) hoping to be able to use it for my use case. 
(Side note, the wiki says `DefaultApiVersionReader `and `ConstantApiVersionReader` in lieu of `DefaultApiVersionSelector` and `ConstantApiVersionSelector`.)

There is a quote saying

>  (it) can be used for other scenarios, it is currently only utilized when no API version is requested by a client and the server allows this behavior.

I was wondering how to configure this to be able to use a custom selector whenever the the requested version is not matched by any of the currently implemented version. 

What I am trying to achieve is to be able to select the latest version available that is not greater than the one specified in the request. 
Example, my API has version `1.0`, `1.1` and `2.0`. If the client requests` 2.1` or `3.0`, the response should be the `2.0` version. If the client specifies `1.2`, the response should be `1.1`. 
I think I could manage to implement it with inspiration from the original answer [here](https://github.com/dotnet/aspnet-api-versioning/issues/498#issuecomment-491332885), but the `SelectVersion()` is never reached when passing in an unsupported version. 

Sorry if I have missed anything in the wiki about this, but I haven't been able to find a solution there.

**Comment by sigridbra** [comment]
I think I finally found an answer to the question here https://stackoverflow.com/questions/69368315/asp-net-api-version-ranges

**Comment by commonsensesoftware** [comment]
It appears that my answer here and linked answer on SO provided a satisfactory solution for you. In the event that it didn't, feel free to ask more questions or re-open the issue.
