### ISSUE TITLE
Semver Versioning

### ISSUE THREAD

**Issue by chris-briddock** [dotnet/aspnet-api-versioning#1004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Can you make it so it conforms to SemVer 2.0

### Describe the solution you'd like

Calling new APIVersion. Will result in something like this:-

using System.Diagnostics.CodeAnalysis;
using static System.String;
using static System.Text.RegularExpressions.Regex;
using static System.Text.RegularExpressions.RegexOptions;
using Microsoft.AspNetCore.Mvc.Versioning;

namespace Microsoft.AspNetCore.Mvc;

/// <summary>
/// Represents the application programming interface (API) version of a service using Semantic Versioning (SemVer).
/// </summary>
public partial class ApiVersion : IEquatable<ApiVersion>, IComparable<ApiVersion>, IFormattable
{
    const int Prime = 397;
    const string ParsePattern = @"^(\d+)\.(\d+)\.(\d+)(?:-(.*))?$";
    int hashCode;

    ApiVersion()
    {
        MajorVersion = 1;
        MinorVersion = 0;
        PatchVersion = 0;
        PreRelease = null;

        hashCode = GetHashCodeInternal();
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="ApiVersion"/> class.
    /// </summary>
    /// <param name="majorVersion">The major version.</param>
    /// <param name="minorVersion">The minor version.</param>
    /// <param name="patchVersion">The patch version.</param>
    /// <param name="preRelease">The pre-release version.</param>
    public ApiVersion(int majorVersion, int minorVersion, int patchVersion, string? preRelease = null)
    {
        if (majorVersion < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(majorVersion));
        }

        if (minorVersion < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(minorVersion));
        }

        if (patchVersion < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(patchVersion));
        }

        MajorVersion = majorVersion;
        MinorVersion = minorVersion;
        PatchVersion = patchVersion;
        PreRelease = preRelease;

        hashCode = GetHashCodeInternal();
    }

    /// <summary>
    /// Gets the default API version.
    /// </summary>
    /// <value>The default <see cref="ApiVersion">API version</see>, which is always "1.0.0".</value>
    public static ApiVersion Default { get; } = new ApiVersion();

    /// <summary>
    /// Gets the major version number.
    /// </summary>
    /// <value>The major version number.</value>
    public int MajorVersion { get; }

    /// <summary>
    /// Gets the minor version number.
    /// </summary>
    /// <value>The minor version number.</value>
    public int MinorVersion { get; }

    /// <summary>
    /// Gets the patch version number.
    /// </summary>
    /// <value>The patch version number.</value>
    public int PatchVersion { get; }

    /// <summary>
    /// Gets the optional pre-release version.
    /// </summary>
    /// <value>The pre-release version.</value>
    /// <remarks>The pre-release version allows services to indicate versions that are not release quality or guaranteed to be backward compatible. Example values might include "alpha", "beta", "rc", etc.</remarks>
    public string? PreRelease { get; }

    /// <summary>
    /// Parses the specified text into an API version.
    /// </summary>
    /// <param name="text">The text to parse.</param>
    /// <returns>The parsed <see cref="ApiVersion">API version</see>.</returns>
    /// <exception cref="FormatException">The specified text is not a valid SemVer API version.</exception>
    [SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Justification = "This is the only type supported.")]
    public static ApiVersion Parse(string text)
    {
        if (TryParse(text, out var result))
        {
            return result;
        }

        throw new FormatException($"The provided version '{text}' is not a valid SemVer API version.");
    }

    /// <summary>
    /// Tries to parse the specified text into an API version.
    /// </summary>
    /// <param name="text">The text to parse.</param>
    /// <param name="version">The parsed <see cref="ApiVersion">API version</see> if successful, or <c>null</c> if parsing fails.</param>
    /// <returns><c>true</c> if the parsing is successful; otherwise, <c>false</c>.</returns>
    [SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Justification = "This is the only type supported.")]
    public static bool TryParse(string text, out ApiVersion? version)
    {
        var match = Match(text, ParsePattern, Compiled | IgnoreCase);
        if (match.Success)
        {
            var major = int.Parse(match.Groups[1].Value);
            var minor = int.Parse(match.Groups[2].Value);
            var patch = int.Parse(match.Groups[3].Value);
            var preRelease = match.Groups[4].Success ? match.Groups[4].Value : null;

            version = new ApiVersion(major,
                                     minor,
                                     patch,
                                     preRelease);
            return true;
        }

        version = null;
        return false;
    }

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is ApiVersion other && Equals(other);

    /// <inheritdoc/>
    public bool Equals(ApiVersion? other)
    {
        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return other != null &&
               MajorVersion == other.MajorVersion &&
               MinorVersion == other.MinorVersion &&
               PatchVersion == other.PatchVersion &&
               Equals(PreRelease, other.PreRelease);
    }

    /// <inheritdoc/>
    public override int GetHashCode() => hashCode;

    int GetHashCodeInternal()
    {
        var hash = MajorVersion;
        hash = (hash * Prime) ^ MinorVersion;
        hash = (hash * Prime) ^ PatchVersion;

        if (!IsNullOrEmpty(PreRelease))
        {
            hash = (hash * Prime) ^ PreRelease!.GetHashCode();
        }

        return hash;
    }

    /// <inheritdoc/>
    public override string ToString() => PreRelease == null
        ? $"{MajorVersion}.{MinorVersion}.{PatchVersion}"
        : $"{MajorVersion}.{MinorVersion}.{PatchVersion}-{PreRelease}";

    /// <inheritdoc/>
    public string ToString(string? format, IFormatProvider? formatProvider) => ToString();

    /// <inheritdoc/>
    public int CompareTo(ApiVersion? other)
    {
        if (ReferenceEquals(this, other))
        {
            return 0;
        }

        if (other is null)
        {
            return 1;
        }

        var majorComparison = MajorVersion.CompareTo(other.MajorVersion);
        if (majorComparison != 0)
        {
            return majorComparison;
        }

        var minorComparison = MinorVersion.CompareTo(other.MinorVersion);
        if (minorComparison != 0)
        {
            return minorComparison;
        }

        var patchComparison = PatchVersion.CompareTo(other.PatchVersion);
        if (patchComparison != 0)
        {
            return patchComparison;
        }

        if (IsNullOrEmpty(PreRelease) && IsNullOrEmpty(other.PreRelease))
        {
            return 0;
        }

        if (IsNullOrEmpty(PreRelease))
        {
            return 1;
        }

        if (IsNullOrEmpty(other.PreRelease))
        {
            return -1;
        }

        return StringComparer.OrdinalIgnoreCase.Compare(PreRelease, other.PreRelease);
    }

    /// <summary>
    /// Determines whether two specified API versions are equal.
    /// </summary>
    /// <param name="version1">The first API version to compare, or <c>null</c>.</param>
    /// <param name="version2">The second API version to compare, or <c>null</c>.</param>
    /// <returns><c>true</c> if the two versions are equal; otherwise, <c>false</c>.</returns>
    public static bool operator ==(ApiVersion? version1, ApiVersion? version2)
    {
        if (ReferenceEquals(version1, version2))
        {
            return true;
        }

        if (version1 is null || version2 is null)
        {
            return false;
        }

        return version1.Equals(version2);
    }

    /// <summary>
    /// Determines whether two specified API versions are not equal.
    /// </summary>
    /// <param name="version1">The first API version to compare, or <c>null</c>.</param>
    /// <param name="version2">The second API version to compare, or <c>null</c>.</param>
    /// <returns><c>true</c> if the two versions are not equal; otherwise, <c>false</c>.</returns>
    public static bool operator !=(ApiVersion? version1, ApiVersion? version2) => !(version1 == version2);

    /// <summary>
    /// Determines whether the first specified API version is less than the second specified API version.
    /// </summary>
    /// <param name="version1">The first API version to compare, or <c>null</c>.</param>
    /// <param name="version2">The second API version to compare, or <c>null</c>.</param>
    /// <returns><c>true</c> if <paramref name="version1"/> is less than <paramref name="version2"/>; otherwise, <c>false</c>.</returns>
    public static bool operator <(ApiVersion? version1, ApiVersion? version2)
    {
        if (version1 is null)
        {
            return version2 is not null;
        }

        return version1.CompareTo(version2) < 0;
    }

    /// <summary>
    /// Determines whether the first specified API version is greater than the second specified API version.
    /// </summary>
    /// <param name="version1">The first API version to compare, or <c>null</c>.</param>
    /// <param name="version2">The second API version to compare, or <c>null</c>.</param>
    /// <returns><c>true</c> if <paramref name="version1"/> is greater than <paramref name="version2"/>; otherwise, <c>false</c>.</returns>
    public static bool operator >(ApiVersion? version1, ApiVersion? version2)
    {
        if (version1 is null)
        {
            return false;
        }

        return version1.CompareTo(version2) > 0;
    }

    /// <summary>
    /// Determines whether the first specified API version is less than or equal to the second specified API version.
    /// </summary>
    /// <param name="version1">The first API version to compare, or <c>null</c>.</param>
    /// <param name="version2">The second API version to compare, or <c>null</c>.</param>
    /// <returns><c>true</c> if <paramref name="version1"/> is less than or equal to <paramref name="version2"/>; otherwise, <c>false</c>.</returns>
    public static bool operator <=(ApiVersion? version1, ApiVersion? version2)
    {
        if (version1 is null)
        {
            return true;
        }

        return version1.CompareTo(version2) <= 0;
    }

    /// <summary>
    /// Determines whether the first specified API version is greater than or equal to the second specified API version.
    /// </summary>
    /// <param name="version1">The first API version to compare, or <c>null</c>.</param>
    /// <param name="version2">The second API version to compare, or <c>null</c>.</param>
    /// <returns><c>true</c> if <paramref name="version1"/> is greater than or equal to <paramref name="version2"/>; otherwise, <c>false</c>.</returns>
    public static bool operator >=(ApiVersion? version1, ApiVersion? version2)
    {
        if (version1 is null)
        {
            return version2 is null;
        }

        return version1.CompareTo(version2) >= 0;
    }
}

**Comment by commonsensesoftware** [comment]
In short, this feature has been asked for in the past and it is unlikely to ever happen. An API version is **not** like a Semantic Version. In fact, one could argue that there's no point in even having support for a minor version, but it's very well-established. A _patch_ version definitely has no place in an API version. An API version is not like a binary version. In fact, it shouldn't be thought of as a _version_ at all (though that's the established vernacular). It is much more like a media type. API versions must be discrete and are aligned to wire contracts. _Patching_ is useful and interesting for binary components, but is meaningless to a client over HTTP. Patches are not to have visible changes. If there is no visible change to a client, then why advertise it and make a client know about it?

Based on your example, it would seem to based off older versions. [IApiVersionParser](../blob/main/src/Abstractions/src/Asp.Versioning.Abstractions/netstandard2.0/IApiVersionParser.cs) was introduced in `6.0` and provides a common abstraction for parsing API versions. That separates parsing from the `ApiVersion` type. This makes it much easier to subclass `ApiVersion` and change it to suiting your needs, such as adding a `PatchVersion` property. Parsing, however, is only part of the picture. You still have to consider hashing, comparison, formatting, and use in attributes. Very few people have been willing to put in the effort to achieve a comprehensive solution.

The only reason that `ApiVersion` is a `class` instead of a `struct` or `interface` is that you cannot extend structures and interfaces could not have operator overloads until C# 11. Ideally, some interface `IApiVersion` would implement `IFormattable`, `IEquatable`, `IComparable`, and have no other members. The reasons `ApiVersion` stayed largely unchanged was for backward compatibility and limitations in the language. I've considered improving things more, but it I have weigh what could result in a significant change.

#990 discusses how to create a custom `ApiVersion`. There is also a link to a Gist that I created that provides a bare minimum working implementation end-to-end. If you really want to support Semantic Versioning, that should be enough to get you started.

**Comment by chris-briddock** [comment]
Could an option be added to the action?

**Comment by commonsensesoftware** [comment]
I'm not sure I follow your question. What would the option be? How would it be applied to an action? What would it look like?

**Comment by commonsensesoftware** [comment]
Last call. Was there any follow up discussion or elaboration that you wanted to provide? Even if there were a way to match a Semantic Version, it probably isn't that valuable. If you have a sound version policy, say `N-2`, what's the value in matching `/value?api-version=1.*`? There would never be more than 3 possibilities. This approach is pretty nonsensical for a date such `/value?api-version=2023-08-01`. It's not clear how you envision this working.
