### ISSUE TITLE
The API Version Conventions documentation appears to be incorrect

### ISSUE THREAD

**Issue by gklittlejohn** [dotnet/aspnet-api-versioning#1016]
The following is shown in the [API Versions conventions documentation ](https://github.com/dotnet/aspnet-api-versioning/wiki/API-Version-Conventions#aspnet-core-1): 

```csharp
services.AddApiVersioning( options =>
{
    options.Conventions.Controller<MyController>().HasApiVersion( 1.0 );
} );
```

I think this should be the following based on the [example application:](https://github.com/dotnet/aspnet-api-versioning/blob/main/examples/AspNetCore/WebApi/ConventionsExample/Program.cs)

```csharp
services.AddApiVersioning()
            .AddMvc(options =>
{
    options.Conventions.Controller<MyController>().HasApiVersion( 1.0 );
});
```

**Comment by commonsensesoftware** [comment]
You're correct. Thank you for that. I will be fixed momentarily.

**Comment by commonsensesoftware** [comment]
It should be correct now. Thanks for point it out.

**Comment by gklittlejohn** [comment]
Thanks, that looks correct.
