### ISSUE TITLE
ApiVersioningOptions UseApiBehavior removal

### ISSUE THREAD

**Issue by GeorgeNarcis** [dotnet/aspnet-api-versioning#1029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to do a migration from 5.1.0 to 6.4.0. In the 5 version we are using in the setup the property UseApiBehavior  from  ApiVersioningOptions.
It seems this has been removed in 6.x.x but I don t find the change anywhere in migration guide or docs.

### Expected Behavior

How should we migrate this ? Is there a default value or do we need to add something else ?

### .NET Version

6

**Comment by commonsensesoftware** [comment]
I was trying to find the release notes on this, but I'm not finding them. `UseApiBehavior` was introduced to support backward compatibility for <= `2.1`.  It was originally `false` and later defaulted to `true`. It was always to slated to be removed at some point. I _think_ that happened in `6.0` and I just forgot to call it out.

The first question is how you are using `UseApiBehavior`. If you're explicitly setting it to `true`, that's the default and current behavior. There's nothing for you to do. You're migrated. 😄 

If you're setting it to `false`, that still exists, but is unusual. The entire point of `UseApiBehavior` was to make it easy to filter API controllers. Setting the configuration value to `false` implies that you are using API Versioning for non-API controllers. This is supported for people that want to do that, but is a bit of an odd case.

At the same time that `UseApiBehavior` was introduced, two new services were also introduced:

- `IApiControllerFilter` - filter down all controllers to just API controllers
- `IApiControllerSpecification` - identify an API controller

There are two built-in _specifications_ one for detecting API controllers by looking for whether the `ApiControllerAttribute` has been applied (aka _API Behaviors_). This can be applied at the controller or assembly level. The second is looking for OData controllers (if you're usng it). The default filter accepts all specifications and removes any that are not satisfied. The old `UseApiBehavior = false` was a shortcut to not using any filtering.

If you truly need custom filtering, you can replace any of the services and/or provide custom filters or specifications. If all you want is the equivalence of `UseApiBehavior = false`, then an empty filter is provided out-of-the-box that you can use to replace the default service like this:

```c#
builder.Services.AddTransient<IApiControllerFilter, NoControllerFilter>();
builder.Services.AddApiVersioning();
```

I will make it a point to add some additional information about this in the migration guide.

A similar question was asked on SO:
https://stackoverflow.com/questions/76602962/what-does-useapibehavior-property-do-in-the-apiversioning-library

**Comment by GeorgeNarcis** [comment]
Hi thanks for the detailed explanation. As it seems we don t need it anymore and was legacy from the beginning of the project
