### ISSUE TITLE
ASP.NET Web API versioning Migrate from QueryStringApiVersionReader to UrlSegmentApiVersionReader

### ISSUE THREAD

**Issue by barbosatekBU** [dotnet/aspnet-api-versioning#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm currently looking into migrate an API versioning mechanism from using query parameter to use url fragments. However, I need to maintain backwards compatibility, so if the caller specifies the version on the query, it fulfills the new url segment on the route. My routes will go from:

[Route("articles")] to [Route("v{version:apiVersion}/articles")]

However, it seems when passing the api version as query parameter, the routing won't find the route (because the version is missing) and it will return 404.

Is there a way to support both, UrlSegmentApiVersionReader and QueryStringApiVersionReader at the same time?

Thanks

### Describe the solution you'd like

Support truly combined version strategies, in this case UrlSegmentApiVersionReader and QueryStringApiVersionReader.

**Comment by commonsensesoftware** [comment]
Sorry to hear you're moving away from the RESTful approach, but I'm sure you have your reasons.

The combination of the `QueryStringApiVersionReader` and `UrlSegmentApiVersionReader` is the default, supported configuration as can be seen here:

https://github.com/dotnet/aspnet-api-versioning/blob/471eb044500495beb8a4f009d9a1c2bf4d5fde63/src/Common/src/Common/ApiVersioningOptions.cs#L75

and here:

https://github.com/dotnet/aspnet-api-versioning/blob/471eb044500495beb8a4f009d9a1c2bf4d5fde63/src/Common/src/Common/ApiVersionReader.cs#L25

I _think_ the misunderstanding is that you have to retain both routes. You can start with the most vanilla configuration:

```c#
builder.Services.AddApiVersioning();
```

Assuming you started with `1.0`, then you might have something like this:

```c#
[ApiVersion(1.0)]
[ApiController]
[Route("[controller]")]
[Route("v{version:apiVersion}/[controller]")]
public class ArticlesController : ControllerBase
{
    [HttpGet]
    public IActionResult Get() => Ok();
}

[ApiVersion(2.0)]
[ApiController]
[Route("v{version:apiVersion}/articles")]
public class Articles2Controller : ControllerBase
{
    [HttpGet]
    public IActionResult Get() => Ok();
}
```

Without any further configuration, you'll now have the following routes:

| Version | URL | Controller |
| -------- | ---- | ----------- |
| `1.0`      |  `articles?api-version=1.0` | ArticlesController |
| `1.0`      |  `v1/articles` | ArticlesController |
| `2.0`      |  `articles?api-version=2.0` | 400 |
| `2.0`      |  `v2/articles` | Articles2Controller |

If you have more versions, then you'll have to continue to repeat this process. Eventually, you'll be able to create single route templates for new versions once the old versions have been completely sunset. I hope that helps clear things up.

**Comment by barbosatekBU** [comment]
Thanks, that answers my question. Closing now.
