### ISSUE TITLE
Different options in `ApiVersioningOptions.cs` between .NET Framework and .NET Core packages

### ISSUE THREAD

**Issue by Saibamen** [dotnet/aspnet-api-versioning#1035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We fixed one bug in our Legacy (but still in active development) .NET Framework WebAPI by setting `ControllerNameConvention = new OriginalControllerNameConvention();`.

Now I want to do the same in .NET Core WebAPI, but `IControllerNameConvention` is missing in `ApiVersioningOptions.cs`...

.NET Framework NuGet name and version: `Microsoft.AspNet.WebApi.Versioning` 5.1.0
.NET Core NuGet name and version: `Asp.Versioning.Mvc.ApiExplorer` 7.1.0

![image](https://github.com/dotnet/aspnet-api-versioning/assets/905878/314f9074-bba6-4bf7-be5c-45a454db8f0a)

### Expected Behavior

.NET Core should have all options from official documentation.
Controller name should be `PrintV2` in Swagger in .NET Core.

![image](https://github.com/dotnet/aspnet-api-versioning/assets/905878/5b16f02c-9d6b-41b2-aa9f-21a019667de6)

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

.NET Core 7.0.13

**Comment by commonsensesoftware** [comment]
This option still exists, but it is now only set through dependency injection (DI). Web API doesn't have out-of-the-box DI support so the option needs to be explicit in the options. In ASP.NET Core, _Minimal APIs_ and MVC Core are separated by the `AddApiVersioning()` and `AddMvc()` respectively. I considered moving `ControllerNameConvention` over to the MVC Core options, but I really wanted to reduce the number of configurable options which are better suited for DI. In fact, the naming convention could always be set via DI. Setting it via the options was a secondary way.

You can find the source at:

https://github.com/dotnet/aspnet-api-versioning/blob/471eb044500495beb8a4f009d9a1c2bf4d5fde63/src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/DependencyInjection/IApiVersioningBuilderExtensions.cs#L66

To achieve your desired configuration, you need only set or replace the service you want to use:

```c#
builder.Services.AddSingleton<IControllerNameConvention, OriginalControllerNameConvention>();
```

In fairness, I missed adding this change to the migration guide. I have updated the section on configuration to note this difference.

I hope that helps.

**Comment by Saibamen** [comment]
Thank you. It works :)
