### ISSUE TITLE
odata/$metadata returns 404 when all controllers are decorated with ApiVersionNeutralAttribute

### ISSUE THREAD

**Issue by cfauchere** [dotnet/aspnet-api-versioning#1060]
When all API controllers are decorated with the ApiVersionNeutralAttribute, the odata/$metadata always return 404. Removing the attribute on a single controller makes the issue go away.
[WebApplication1.zip](https://github.com/dotnet/aspnet-api-versioning/files/13636281/WebApplication1.zip)

**Comment by commonsensesoftware** [comment]
There wasn't any additional follow-up or push-back. This behavior is expected and is an unfortunate limitation and edge case that is effectively nonsensical in a real application. I _could_ document this as a known limitation if you feel it is warranted. It's such a bizarre use case, I never thought anyone would actually hit it.

**Comment by commonsensesoftware** [comment]
This behavior is expected albeit not as obvious as one might expect. The discussion appears to have gone idle and I don't think there's any more to do. If there, feel free to reopen the issue.
