### ISSUE TITLE
HttpConfigurationExtensions methods missing?

### ISSUE THREAD

**Issue by nirzamir** [dotnet/aspnet-api-versioning#245]
Hi,
I have Microsoft.AspNet.WebApi.Versioning.dll version 2.2.6579 downloaded from nuget a couple of weeks ago.

I'm trying to use HttpConfiguration `AddVersionedApiExplorer` method (as described [here](https://github.com/Microsoft/aspnet-api-versioning/wiki/API-Documentation)), but the compiler can't find it.
When I browse into the dll, I see that the `HttpConfigurationExtensions class `has only `AddApiVersioning `and `GetApiVersioningOptions `methods, and no sign of `AddVersionedApiExplorer`... 

I also can't find ApiDescriptionExtensions so ApiDescription.GetGroupName is also missing...

What am I missing here?

Thanks!

**Comment by commonsensesoftware** [comment]
Ah ... the API Explorer support is in a separate, but complementary NuGet package. I tried to make that easy to follow on the landing page, but I see how it can be easily missed from looking at just the wiki or code samples.

For Web API, you need this package as well: [Microsoft.AspNet.WebApi.Versioning.ApiExplorer](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Versioning.ApiExplorer).

There are similar packages for OData and ASP.NET Core should you need those as well.

**Comment by nirzamir** [comment]
Thanks for the quick response!
