### ISSUE TITLE
Api versioning on Endpoint routing

### ISSUE THREAD

**Issue by fzan** [dotnet/aspnet-api-versioning#559]
Hello,

I was wondering if something like this library, actually working with MVC routing, is available on Endpoint routing on ASPNET Core 3.0, or even if a future porting of aspnet-api-versioning is on the roadmap.

Thanks

**Comment by commonsensesoftware** [comment]
Endpoint routing is already supported and is the default. It has been that way for some time. ASP.NET Core 3.0 is supported in the [preview](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning/4.0.0-preview8.19405.7). I'm hoping have it shipped this week. There's no additional work, bugs, or changes, it's just a matter if preparing the release. I'm a one-man shop.

I'm not sure if you meant something more by _MVC routing_. If you're asking about whether you can use API versioning with UI controllers, then - yes - it's possible, but a bit odd. You'll have to change to default conventions to include such controllers as they are filtered about by default (as many people have asked for).

Does that clarify things?

**Comment by fzan** [comment]
It absolutely help :-)

I enabled the nuget preview packages, used the 4.0 branch, added the service middleware and it works :-)

I really appreciate your kind answers and your support, again many thanks
