### ISSUE TITLE
Case Sensitive Request Body

### ISSUE THREAD

**Issue by spotnick** [dotnet/aspnet-api-versioning#723]
Hi,

I wanted to ask, why when sending a Post request the body has to be case sensitive? After implementing API Versioning I encounter the strange behaviour that all attributes in the request body have to start with capital letter or with lowercase depending on how the VersionedODataModelBuilder was modified in startup. While I was only using OData without Versioning everything was fine. Even Newtonsoft.Json doesnt bother it most of the time which case the attributes are.

How can I achieve that behavior? Is it even possible? I dont want my customer to bother with cases of the attributes.

Thanks a lot! :-)

Best regards
Thomas

**Edit:**

Some additional information here what I found:

Odata should support case insensitive request bodies with the newest release, as discussed here: https://github.com/OData/WebApi/issues/2247

And should already be merged into the latest release:
https://github.com/OData/WebApi/pull/2311

I also updated the code of aspnet-api-versioning but I cant get it to run. I cannot find where the properties of the request body is compared to the model. I´m totally out of ideas. Hoping someone can fix it :-)

**Comment by commonsensesoftware** [comment]
This issue appears to reached its conclusion and is an issue directly in OData. To my knowledge, the OData has fixed their implementation and this is no longer an issue. I'm going to close this out, but if you feel it's in error, feel free to reopen it. Thanks.
