### ISSUE TITLE
SwaggerODataSample throws Exception when accessing V1, V2 and V3

### ISSUE THREAD

**Issue by andenkondor** [dotnet/aspnet-api-versioning#729]
Hi,

I'm currently on v5.0.0 and can't access the swagger docs for every version greater than 0.9.
Here is what the log is telling me:

`Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - Microsoft.Examples.V1.OrdersController.Post (SwaggerODataSample). See inner exception
 ---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate schema for type - Microsoft.Examples.Models.Order. See inner exception
 ---> System.InvalidOperationException: Can't use schemaId "$Order" for type "$Microsoft.Examples.Models.Order". The same schemaId is already used for type "$Microsoft.Examples.Models.Order"
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.RegisterType(Type type, String schemaId)`

**Comment by Janus88** [comment]
Hi,

I encountered the same problem. As a workaround, downgrading Swashbuckle.AspNetCore Nuget package to 5.6.3 helped.

**Comment by icnocop** [comment]
Does the `Post` action have `[ProducesResponse(StatusCodes.Status200OK, Type = typeof(ODataValue<IQueryable<Order>>))]` ?

**Comment by nsunmaz** [comment]
I found the solution but couldn't find the couse.

```
services.AddSwaggerGen(opt =>
{
   ...
   opt.CustomSchemaIds(type => type.ToString() + type.GetHashCode()); // This helped me
   ...
});
```

**Comment by commonsensesoftware** [comment]
I've discovered that this specific issue is a bug in Swashbuckle. Updating to the latest release should fix this. You _might_, however, run into other issues related to route template generation (not model generation). Peek at the updated sample in [this branch](../tree/dev/css/201606-fixes). That _may_ address them until the next patch is released.
