### ISSUE TITLE
PostTo Issue

### ISSUE THREAD

**Issue by strandman** [dotnet/aspnet-api-versioning#742]
According to [built-in-routing-conventions](https://docs.microsoft.com/en-us/odata/webapi/built-in-routing-conventions) you should be able to Post to Navigation Collection Properties.

But it seems like #573 is hard coded to "CreateRef":
[ODataRouteBuilderContext.cs](https://github.com/microsoft/aspnet-api-versioning/blob/master/src/Common.OData.ApiExplorer/AspNet.OData/Routing/ODataRouteBuilderContext.cs#L127)

Valid Post actions on collection navigation properties is also:
`PostTo{PropertyName}` and `PostTo{PropertyName}From{EntityName}`

**Comment by strandman** [comment]
> Is there actually an issue or you just made an observation?
The place where this looks like it _might_ be an issue is inside `IsNavigationPropertyLink`. It covers `{HttpMethod}{PropertyName}`, but not `{HttpMethod}To{PropertyName}`

Yes it is an issue because [ODataActionDescriptorProvider.cs#L55](https://github.com/microsoft/aspnet-api-versioning/blob/master/src/Microsoft.AspNetCore.OData.Versioning/AspNetCore.Mvc/ODataActionDescriptorProvider.cs#L55) removes the ActionDescriptor and It'll not be readded because   `IsRouteExcluded = ActionType == ODataRouteActionType.Unknown` and will never hit [ODataRouteBindingInfoConvention.cs#L156](https://github.com/microsoft/aspnet-api-versioning/blob/master/src/Microsoft.AspNetCore.OData.Versioning/AspNet.OData/Routing/ODataRouteBindingInfoConvention.cs#L156). `PutTo` and `PatchTo` works simply because [ODataRouteBuilderContext.cs#L127](https://github.com/microsoft/aspnet-api-versioning/blob/master/src/Common.OData.ApiExplorer/AspNet.OData/Routing/ODataRouteBuilderContext.cs#L127) ignores those verbs.
> > The documentation for OData conventions is useful, but I don't trust it due to painful history lessons. I reference the conventions/templates found directly in the code as the source of truth.

Yes I understand, the navigation template you should look at is: [NavigationRoutingConvention.cs#L85](https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Routing/Conventions/NavigationRoutingConvention.cs#L85)

Sorry for bad grammar, I'm not an English speaking person ;)

**Comment by commonsensesoftware** [comment]
Thanks for the confirmation. It looks like this use case is indeed missed so I'm going to go ahead and mark it as a bug.
