### ISSUE TITLE
ExceptionHandlerMiddleware does not clear IApiVersioningFeature

### ISSUE THREAD

**Issue by mattvperry** [dotnet/aspnet-api-versioning#748]
I originally filed this issue over on the aspnetcore side here:
https://github.com/dotnet/aspnetcore/issues/33302

The original details are present there for reference. However, the discussion has raised some questions about the implementation details of ApiVersioning that I haven't been able to answer. Any help driving this issue to a conclusion either from this end or theirs would be much appreciated.

**Comment by commonsensesoftware** [comment]
Tracking a generic enhancement for this as #749
