### ISSUE TITLE
OData service with hierarchy recursion

### ISSUE THREAD

**Issue by AndrewZenith** [dotnet/aspnet-api-versioning#760]
I'm trying to generate my Swagger Pages for my OData Service (using 8.0.1).  My EdmModel has hierarchy recursion, and I can see the PseudoModelBindingVisitor.Visit is going nuts as a result.  I debugged, and at the below line it's already gone into recursive madness.

How do I stop this.  I don't mind if I just get the base object (for now) in the swagger page - I just want it to generate!  I don't want to change the EdmModel though, it's working fine and will let me down into the navigation properties.

Visit(context, bindingSource ?? ambientSource, containerName2);

containerName2, already gone down the rabbit hole:

ClientIDXpo.ClientAdditionalDetailsNewXpo.ServiceIDXpo.FclaspServicesXpo.CountryIDDestXpo.CsdAddSecIDXpo.UpdateUserIDXpo.UserPasswordXpo.UpdateUserIDXpo.ClientIDFclaspXpoDs.ClientDefRegistAndApprovalXpoDan1.RegappcatIDXpo.RegappIDXpo.UpdateUserIDXpo.SubsidiarySystemUsersXpo.UpdateUserIDXpo.StklocIDXpo.CountryIDXpo.CurrencyIDXpo.CountryIDXpo.DoctxtIDExpSpotQuoteCat2Xpo.AnalysisIDXpo.DepartmentIDEmail1Xpo.FilterIDDefEqcGXpo.UpdateUserIDXpo.CliCont3IDXpo.ClientIDXpo.SalesReportsLastContact.ServiceIDXpo.AnalysisIDXpo.DepartmentIDEmail2Xpo.ServiceIDXpo.BerthsIDXpo.ClientIDclearXpo.CRMBatchControlListHoldingXpo.ClientIDXpo.ZipCodesXpo.CountryIDXpo.DoctxtIDExpSpotQuoteCat3Xpo.CreateUserIDXpo.AnalysisIDCrmXpo.DepartmentIDEmail3Xpo.AnalysisIDClientVisibleXpo.DepartmentIDEmail4Xpo.AnalysisIDDeptTypeXpo.DocmaskIDXpo.DataType.Assembly.EntryPoint.ReturnParameter.Member

**Comment by commonsensesoftware** [comment]
OData `8.0` is not officially supported so hopefully that isn't the culprit.

Do you have the file and line number reference link? If you have the world's simplest repro, that would help.

**Comment by AndrewZenith** [comment]
PseudoModelBindingVisitor.Visit Just keeps going into PseudoModelBindingVisitor.Visit.

Doesn't matter that the datatypes have already been found, it just keeps going down the chain.
I'll see if I can put something together with EF, but at the simplest class thing has a property thing that is a thing.  Container name becomes thing.thing.thing.thing.thing........  ad infinitum.
I tried using the swagger IFilterSchema, but it never gets called in my scenario, as I think it's post schema generation.  I need something to stop it!

**Comment by AndrewZenith** [comment]
https://github.com/microsoft/aspnet-api-versioning/blob/e16b579d240574053ebd8e7ee38c8686beaee174/src/Microsoft.AspNetCore.OData.Versioning.ApiExplorer/AspNetCore.Mvc/ApiExplorer/PseudoModelBindingVisitor.cs#L71

**Comment by commonsensesoftware** [comment]
Something is seemingly awry. I haven't seen this before so there is clearly some edge case not covered. The **PseudoModelBindingVisitor** was forked from [here](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs#L491). Perhaps there's some difference or change that has been overlooked.

If only the OData team supported the API Explorer... 🙄

**Comment by kudam5** [comment]
`client_id=tracker.fleet.app
&code=232930E4170ADBF61CEC7491D03394D978A87F32A5B364840EC81F3B9420E706
&redirect_uri=https://qafleet.tracker.co.za/auth-callback
&code_verifier=6e9c7f5450f549f7afbb2eab5abd41830abfcae2876c46d68b4a70c212d76326e94d1e594bd14221944295f386994a1d`

**Comment by commonsensesoftware** [comment]
Circling back around on this issue. I expect that you never got it to work; at least, not the way you wanted. OData 8.0 hasn't been supported (until now) and it was a complete rewrite.  This type of issue, therefore, wasn't too surprising to me.

The `6.0` release is finally close and _will_ support OData 8. You can find the latest code and example for OData + OpenAPI [here](../tree/main/examples/AspNetCore/OData/ODataOpenApiExample). I know it's a bit to ask, but if you're able to test it out and let me know if it addresses your issue, I'm sure it will beneficial to you as well as others. Due the entire rewrite of the OData implementation, the offending line of code mentioned here doesn't event exist anymore.

Here's to hoping this is resolved for you - soon, if it isn't already.

**Comment by commonsensesoftware** [comment]
`6.0` has been officially release. This thread seems to gone dark. Since the offending code no longer even exists, I'm inclined to close this out. If someone this is not resolved, I'm happy to reopen the issue or discuss further. Thanks.
