### ISSUE TITLE
AspnetCore 3.1 API giving UnsupportedApiVersion unexpectedly

### ISSUE THREAD

**Issue by nkamenar** [dotnet/aspnet-api-versioning#773]
I have set up what I think is a nice structure for creating multiple versions of an API. I have decided to support versioning strictly via URI sigment (ie: /api/v1/records). I am also generating swagger docs for the API versions. The doc generation seems to be working fine but for some reason I am only able to reach my v1 endpoints. When I try to hit those everything works fine, but when I try to hit a v2 endpoint I am getting:

```
"Error": {
    "Code": "UnsupportedApiVersion",
    "Message": "The HTTP resource that matches the request URI 'https://localhost:5001/api/v2/records' is not supported.",
    "InnerError": null
}
```

I have created a simple reproduction of the problem in [this repo](https://github.com/nkamenar/AspnetCoreApiError.git). If you navigate to the /swagger page and try v1 or v2 you will see that v1 works but v2 does not. Is this a bug or am I missing something?

**Comment by commonsensesoftware** [comment]
I believe this question has been adequately answered and has reached its conclusion. Feel free to comment or reopen the issue if it's unresolved. Thanks
