### ISSUE TITLE
Cannot use default version (Not specify) bug

### ISSUE THREAD

**Issue by rlgordey** [dotnet/aspnet-api-versioning#774]
I have this in my Startup.cs`:

```csharp
services.AddApiVersioning(config =>
{
    // Specify the default API Version as 1.0
    config.DefaultApiVersion = new ApiVersion(1, 0);
    // If the client hasn't specified the API version in the request, use the default API version number 
    config.AssumeDefaultVersionWhenUnspecified = true;
    // Advertise the API versions supported for the particular endpoint
    config.ReportApiVersions = true;
});
```
However, in an xUnit Test this works:
```csharp
var request = new HttpRequestMessage(HttpMethod.Post, "/api/v1/Users/AuthenticateUser")
```
This does not:
```csharp
var request = new HttpRequestMessage(HttpMethod.Post, "/api/Users/AuthenticateUser")
```

Why do I have to have a version number when I have a default set?

Microsoft.AspNetCore.Mvc.Versioning 5.0.0

C:\Users\rgord>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21427.6
 Commit:    d12ee190bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21427.6\

Host (useful for support):
  Version: 6.0.0-rc.2.21427.5
  Commit:  efe56d6f97

.NET SDKs installed:
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.206 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21427.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21427.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21427.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21427.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by rlgordey** [comment]
> More information, background, and possible alternatives can be found in the [URL Path Segment Routing with a Default API Version](../wiki/Known-Limitations#url-path-segment-routing-with-a-default-api-version) wiki topic.

I get an `System.InvalidOperationException`  when following the wiki for Asp.Net Core...

```
Error 1:
Attribute routes with the same name ''GetFeaturedItemsAsync'' must have the same template:
Action: ''EcommerceWebAPI.Controllers.v1.ItemsController.GetFeaturedItemsAsync (EcommerceWebAPI)'' - Template: ''api/Items/GetFeaturedItems''
Action: ''EcommerceWebAPI.Controllers.v1.ItemsController.GetFeaturedItemsAsync (EcommerceWebAPI)'' - Template: ''api/v{version:apiVersion}/Items/GetFeaturedItems''
```

My controller:
```csharp
  [Consumes(MediaTypeNames.Application.Json)]
  [Produces(MediaTypeNames.Application.Json)]
  [ApiVersion("1.0")]
  [Route("api/[controller]")]
  [Route("api/v{version:apiVersion}/[controller]")]
  [ApiController]
  public class ItemsController : ControllerBase
  {
        [ProducesDefaultResponseType]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]        
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(IEnumerable<EcommerceItemDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [Authorize]
        [HttpGet("GetFeaturedItems", Name = nameof(GetFeaturedItemsAsync))]        
        public async Task<IActionResult> GetFeaturedItemsAsync()
        {
            ...
        }
  }
```

**Comment by commonsensesoftware** [comment]
This is the result of naming your routes.

First, you should be aware that the route table mapping and lookup is **not** API version-aware. Someday it _might_ be, but it's not an easy problem to solve. There are a few possible alternatives:

### No Named Routes
Simply ditching the `Name = nameof(<method>)` will address the immediate problem. The route table expects one name per route, but you now have name and version per route. There's no intrinsic API that can address this out-of-the-box.

### Use Action Names Instead of Route Names
Within a controller, the best way to solve this is to use one of the variants that uses the action name instead of the route name; for example, `CreatedAtAction`. This will use the method/action name which is locally distinct to the controller.

### Refactor to Produce Distinct Route Names
If you really need to create route table entries for lookup, then the only way I know to make it work is to refactor the way the routes templates are generated. This will work:

```c#
  [Consumes(MediaTypeNames.Application.Json)]
  [Produces(MediaTypeNames.Application.Json)]
  [ApiVersion("1.0")]
  [Route("api")]
  [ApiController]
  public class ItemsController : ControllerBase
  {
        [ProducesDefaultResponseType]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]        
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(IEnumerable<EcommerceItemDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [Authorize]
        [HttpGet("[controller]/GetFeaturedItems", Name = "GetFeaturedItems")]
        [HttpGet("v{version:apiVersion}/[controller]/GetFeaturedItems", Name = "GetFeaturedItemsV1")]
        public Task<IActionResult> GetFeaturedItemsAsync() => Ok();
  }
```

There _might_ be a more _convenient_ way to map the templates. This limitation is just one more issue in versioning by URL segment. It's also important to note that you'll still have to use the route name `GetFeaturedItems`, `GetFeaturedItemsV1`, or whatever convention you come up with. The mapping may prove that generating routes from your own mechanisms is easier to manage. Ultimately, that call is yours and your mileage may vary.

>**Side note**: I noticed that you're still using the `Async` suffix in your controller actions. Beware the breaking change in ASP.NET Core 3.0 regarding [Async suffix trimmed from controller action names](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore#mvc-async-suffix-trimmed-from-controller-action-names). That _may_ cause yet another related, but completely different issue.

**Comment by commonsensesoftware** [comment]
This question appears to have been sufficient answered with a solution. It's been quite some time without any follow up. If the provided solution did not work, feel free to comment or reopen the issue and the discussion can resume. Thanks.
