### ISSUE TITLE
.net 6 and openapi versioning is not supported

### ISSUE THREAD

**Issue by developer9969** [dotnet/aspnet-api-versioning#793]
Hi 
Wondering if this approach works in .net6 I put an example together in .net 6 and swagger was not happy at all and I have even raised an issue here https://github.com/dotnet/aspnetcore/issues/37993 with repo project

Should it work in .net 6 or did I made a mistake on my side?

**Comment by commonsensesoftware** [comment]
Currently, it does not - officially anyway.

Long story short, I'm no longer with Microsoft and I'm working to reclaim full control of all parts of the project as to not disrupt the community. The last remaining part is ironing out the NuGet packages. There was a push to use all new package identifiers, which I was not ok with as I feel it's too much disruption to the community (with 83+ million downloads to date). I've been waiting to post something in the discussions that will outline the roadmap until I knew for sure everything was going the land as expected. 

Supporting .NET 6.0 is a infrastructure problem, not a code problem. At the moment, there's no one that can publish updated packages. ☹️ I've been working with the NuGet team. I hope to have this resolved - soon. Getting package out that targets .NET 6.0 is a top priority - for me.

Thanks for your patience.

**Comment by developer9969** [comment]
@commonsensesoftware Thank you very much for your reply. Is there anything that we can do to make it work at our end or is it something that has to be done by the nuget package?

It took me months to persuade management to upgrade from .net framework to .net 6 and now I am stuck on this.

Any workaround?
thanks

**Comment by shrtcrt** [comment]
You can still use this with .net 6. 

1) You could use the earlier ways of Program.cs and StartUp.cs, these still work fine.

2) You can use the new minimal Program.cs (as shown belonw) and still use a StartUp.cs or other class.

Just add support as normal. This is what I did and it still works just fine.

`using Microsoft.AspNetCore.Builder;

var builder = WebApplication.CreateBuilder(args);

var startup = new Startup(builder.Configuration);

startup.ConfigureServices(builder.Services);

var app = builder.Build();

startup.Configure(app, app.Environment);

app.Run();
`

**Comment by commonsensesoftware** [comment]
@shrtcrt thanks. I presume you, or perhaps someone else in the community, can confirm that things actually compile.

The only potential barriers _should_ be breaking changes between the .NET 5 vs 6 for ASP.NET Core. I'm not currently aware of any; at least, not any that would affect API Versioning. As long as that works, you should be golden. Anything else about `Startup.cs` and so on is primarily compiler _magic_ and syntactic _sugar_ that API Versioning doesn't care about.

There has been an ask to support _Minimal APIs_, but that is on the backlog. I haven't tried it - yet, but another option is to take a private fork, retarget to `net6.0`, build it, and run from that. It's lame, but if that unblocks you, it's a possible option.

>It looks like I'm really close to unblocking at least one part of the NuGet battle. This would enable me to publish again. I'll need to finish onboarding to DNF in order to re-enable code signing. _I_ feel it's important, but I don't know how important is it is to the community. If that is deemed a show-stopper, then I'll move to a RC release which is unsigned until I can resolve those impediments.

**Comment by shrtcrt** [comment]
@commonsensesoftware I can confirm it compiles and has been deployed into our production environment. So far no issues there. I took a .net 5 project, changed Program.cs to use the new minimal api start, used my existing Startup.cs file and added the code as above.

**Comment by developer9969** [comment]
@shrtcrt Hi there may be I am missing the obvious and I have probably done something wrong.
I have built a small repo project with  3 versions V1-V2-V3 

1. Download the repo https://github.com/developer9969/WebApiNet6VersioningIssue
2. You will see that there are 3 version V1-V2-V3 
3. Each version has a "PeopleController" and for some reason it does not work in .net 6 but does in .net 5
3. Launch the webapi
4. Swagger V1 Definition is fine
5. Select V2 or V3 definitions and you will see an error.

Are you saying I need to add program.cs?  I have been stuck on this one for weeks now , do you mind having a look at simple repo ?

thanks

**Comment by shrtcrt** [comment]
@developer9969 I grabbed your repo and it ran just fine. I was able to hit all three endpoints with no errors.

What errors are you seeing? The swagger files for V2 and V3 don't work, but v1 did. I just called the 3 endpoints via a browser.

api/v1.0/people
api/v2.0/people
api/v3.0/people

**Comment by Jens-H-Eriksen** [comment]
@developer9969 this issue seems to be related to Swagger only. I have the same problem and only my V1 version is working in Swagger. It is possible to reach the V2 and V3 versions with fx. Postman though, so other than Swagger everything is working fine.

**Comment by developer9969** [comment]
@shrtcrt  swagger is not working try to switch the versions in swagger. How can I make it work with swagger
@Jens-H-Eriksen  

> It is possible to reach the V2 and V3 versions with fx.     

what fx is required?

**Comment by Jens-H-Eriksen** [comment]
Sorry.. my bad: "_fx._ Postman" = "_for example_ Postman"
Swagger does not work for the V2 and V3 in my solution. But you kan still reach the endpoints though. For testing that, I use Postman.

**Comment by johnfriedrich** [comment]
Csn confirm that it seems to be a swagger only issue. I can switch versions in Swagger just fine, but getting a 404 when trying out any endpoint with any version. Even V1 does not work. But we dont have a default Api version set, which may be the cause for that. But can reach endpoints via Postman/client just fine

**Comment by developer9969** [comment]
**Quick gif of not working in swagger**
![SwaggerGifApiVersioning](https://user-images.githubusercontent.com/16970109/143038637-2afe0989-b56f-446a-8337-748adcbbd1ef.gif)

**Working in postman**
![PostmanGifApiVersioning](https://user-images.githubusercontent.com/16970109/143039345-6d7e0199-b061-4040-8137-ffeb45af0724.gif)

**Comment by shrtcrt** [comment]
@developer9969 Well that makes more sense, so the real problem is Swagger and not using the versioning with routes in general.

I can take a look later.

**Comment by developer9969** [comment]
@shrtcrt thanks really appreciate any help on this..

**Comment by commonsensesoftware** [comment]
Thanks everyone for hopping in. ❤️ the community support. 

@developer9969 the reason _why_ this is happening is that you've missed a critical step. There's a bit of a _Chicken or The Egg_ problem with the way Swashbuckle's configuration works. In order to use the API Versioning information provided for the API Explorer with Swashbuckle, you need to the _defer_ the configuration using `IConfigureOptions<SwaggerGenOptions>` so that DI can finish its work. Once that's done, you can generate the OpenAPI documents from that point. It might seem strange, but there's two parts to what Swashbuckle does: 1) setup routes to the OpenAPI documents, 2) configure/define the OpenAPI documents themselves. You've defined the routes, but not the documents. I'm not 100% sure why _any_ of them work, but I presume it's due to some default (ex: `V1`) that Swashbuckle wires up.

Configuring the options is pretty simple and looks like [this](../blob/master/samples/aspnetcore/SwaggerSample/ConfigureSwaggerOptions.cs). Once you have that defined, you register it with DI so Swashbuckle picks it up like [this](../blob/master/samples/aspnetcore/SwaggerSample/Startup.cs#L57). After that is in place, all of the documents _should_ start working from the dropdown.

I hope that helps.

**Comment by shrtcrt** [comment]
@commonsensesoftware this is hands down, one of my all time favorite nuget packages. I have been using it for years for all of my api projects.  I look forward to its continued growth!

**Comment by developer9969** [comment]
@commonsensesoftware THANK YOU. All works now . also A big thank you to everyone else who commented on this one.
