### ISSUE TITLE
Do Microsoft.AspNetCore.OData.Versioning.ApiExplorer supports net6.0

### ISSUE THREAD

**Issue by kranthikumar-kvs-by** [dotnet/aspnet-api-versioning#800]
Do Microsoft.AspNetCore.OData.Versioning.ApiExplorer supports net6.0 ?
Any roadmap?

From Package Manager, I can see - 
Microsoft.AspNetCore.OData supports till net5.0
Microsoft.AspNetCore.OData.Versioning.ApiExplorer supports till .net3.1

Please provide some information.

**Comment by commonsensesoftware** [comment]
Officially - no. I believe some people may have gotten it to work, but there are no guarantees expressed or implied. API Versioning currently does not support OData on .NET 5.0 or 6.0, but it is on the roadmap. There is a deeper history, but there are many internal breaking changes to make that work.

I hope and plan to make a formal announcement for the roadmap in plan in the next week or so. Stay tuned. 😃 

>It should be noted that I am neither part of the OData team nor ASP.NET team.  The **Microsoft.AspNetCore.OData** package is owned by the OData team.

**Comment by kranthikumar-kvs-by** [comment]
@commonsensesoftware, thanks for quick update.

**Comment by commonsensesoftware** [comment]
@wenz Gosh time flies. It hasn't been made, but I am literally in the process of writing it up. There's several big announcements coming, including the roadmap. I really, really hope it have it out by tomorrow. I plan to put a banner up on the landing page too (at least for a while to make it obvious). I intend to post it in the Discussions. Thanks for your patience

**Comment by wenz** [comment]
@commonsensesoftware no rush - and thanks for the super quick reply! :)

**Comment by commonsensesoftware** [comment]
@wenz, @kranthikumar-kvs-by

Some [big announcements](../discussions/807) have been made and the [6.0 Roadmap](../discussions/808) has been published. If you just can't wait, you can find latest .NET 6.0 + OData 8 examples [here](../tree/main/examples/AspNetCore/OData), including an OpenAPI example [here](../tree/main/examples/AspNetCore/OData/ODataOpenApiExample).

I'm in the process of burning down all the issues. I don't think there is really any more to discuss here so I'm going to close it out. If you comment more, I'll reply; however, discussions for the upcoming release and roadmap will be better served into those _discussions_. Thanks.
