### ISSUE TITLE
NU1202: Package Asp.Versioning.OData.ApiExplorer 6.0.0-preview.2 is not compatible with netcoreapp3.1

### ISSUE THREAD

**Issue by icnocop** [dotnet/aspnet-api-versioning#815]
Hi.

Thank you for your continued support.

I wanted to test out the new 6.0 package, but I'm getting the following error when trying to add the NuGet package to my web application which targets ASP.NET Core 3.1 from within Visual Studio's NuGet Package Manager.

`NU1202: Package Asp.Versioning.OData.ApiExplorer 6.0.0-preview.2 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Asp.Versioning.OData.ApiExplorer 6.0.0-preview.2 supports: net6.0 (.NETCoreApp,Version=v6.0)`

Is this expected?

I didn't notice in the [6.0 roadmap](https://github.com/dotnet/aspnet-api-versioning/discussions/808) that ASP.NET Core 3.1 is no longer being supported, so I'm thinking maybe it's just an issue with the NuGet package specification.

Thank you.

**Comment by commonsensesoftware** [comment]
Currently - yes - this is expected, but only because I didn't realize that the OData packages were still targeting .NET Core 3.1 It's a goof on my part. Since .NET Core 3.1 is LTS I don't have a problem continuing to support it. I'll mark this as a bug and include that target in Preview 3.

Thanks for reporting this.

>It's worth noting that .NET Core 3.1 falls out of support 12/3/2022, which will be just after .NET 7.0 is released. That will likely mean that it will be dropped from the API Versioning `7.0` release.
>
>https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core

**Comment by commonsensesoftware** [comment]
_Preview 3_ is now available and there is a target for .NET Core 3.1. This issue did not auto-resolve because `main` isn't the default branch - yet. If everything works as you expect, feel free to close it out.

**Comment by commonsensesoftware** [comment]
`6.0` has been officially released and .NET Core 3.1 is a supported TFM. It will remain that way until it is officially dropped by Microsoft support at the end of the year. Expect this to happen around the .NET 7.0 release timeline. Thanks for your contributions.
