### ISSUE TITLE
Attribute routing question

### ISSUE THREAD

**Issue by Mhirji** [dotnet/aspnet-api-versioning#818]
Hello @commonsensesoftware ,

First off, thanks for your great work on this project!! :)

I am looking at the ODataOpenApiExample and had a question.  It appears that when you specify a route as part of the HttpGet/HttpPost attributes on a controller, they do not get generated as part of the OpenApi/Swagger doc.  For example, on the People controller for v2 and v3, the following actions are not documented:

    [HttpGet( "api/People/NewHires(Since={since})" )]
    [Produces( "application/json" )]
    [ProducesResponseType( typeof( ODataValue<IEnumerable<Person>> ), Status200OK )]
    public IActionResult NewHires( DateTime since, ODataQueryOptions<Person> options ) => Get( options );

    [HttpGet( "api/People/{key}/HomeAddress" )]
    [Produces( "application/json" )]
    [ProducesResponseType( typeof( Address ), Status200OK )]
    [ProducesResponseType( Status404NotFound )]
    public IActionResult GetHomeAddress( int key ) =>
        Ok( new Address()
        {
            Id = 42,
            Street = "123 Some Place",
            City = "Seattle",
            State = "WA",
            ZipCode = "98101",
        } );

    [HttpGet( "api/People/{key}/WorkAddress" )]
    [Produces( "application/json" )]
    [ProducesResponseType( typeof( Address ), Status200OK )]
    [ProducesResponseType( Status404NotFound )]
    public IActionResult GetWorkAddress( int key ) =>
        Ok( new Address()
        {
            Id = 42,
            Street = "1 Microsoft Way",
            City = "Redmond",
            State = "WA",
            ZipCode = "98052",
        } );

I am wondering if I am missing something or if there is an issue somewhere? 

Thanks again!

**Comment by commonsensesoftware** [comment]
Thanks for reporting this. I'll look into it. I wouldn't be surprised if I made a mistake or overlooked something. The OData routing story has gotten _better_, it's still not consistent or obvious when you need attributes and when you don't. The good part now is that when something is missing, I know for sure that it's because it didn't match what OData expected. API Versioning no longer does and route template building for OData 🎉. That should help track down errors as well as report any issues back to the OData team.

**Comment by commonsensesoftware** [comment]
You appear to be working from the correct example project. Are you using `preview.1` or `preview.2`? I'm working on `preview.3` now, but I went back to the previous state and I see it documenting these APIs as expected:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/11765008/164558706-ad902815-5490-4331-acc4-beac6e35485c.png">

>_Figure 1: ODataOpenApiExample for API version 3.0_

Have you changed the project in any way? It's possible you're hitting an edge case that I've fixed.

**Comment by Mhirji** [comment]
Last I checked it is preview 2, but will need to confirm.  Hopefully  preview 3 fixed it.  Will confirm the version  I used tomorrow morning.

**Comment by Mhirji** [comment]
Its using preview 2.  Strange that it is working for you.  Will wait for 3 and try again.  Thank you for looking into it and sorry if I wasted some of your time.

**Comment by Mhirji** [comment]
took the latest version of the same project and you are correct, it does work!

**Comment by commonsensesoftware** [comment]
Great! I don't mind. There aren't a lot of addition eyes reviewing this stuff and I do make mistakes. OData, in particular, has a very large test matrix and it's hard to test, show, or automate every possible combination. Thanks.
