### ISSUE TITLE
Multiple versions of Orders Controller and routes not found

### ISSUE THREAD

**Issue by rgtek** [dotnet/aspnet-api-versioning#825]
On the project ODataOpenApiExample, it appears that the OrdersController V3 is not working correctly. For example, both the Patch request and the Get request return a 404. See screenshots below. May be I am missing something?

![Orders Get](https://user-images.githubusercontent.com/65788062/165406347-d30500ca-266e-463d-a67b-4d6853841699.png)

![Orders Patch](https://user-images.githubusercontent.com/65788062/165406492-2ae07e98-47ba-49c9-a200-b508299ec420.png)

**Comment by commonsensesoftware** [comment]
Strange, but not impossible. I'll investigate. Thanks for reporting it.

**Comment by rgtek** [comment]
Yeah... I thought so. The only way I was able to get V3 to work was just by changing the OrderModelConfiguration as below even though it seems to follow the same pattern as the PersonModelConfiguration which does not appear to be affected.

`public void Apply( ODataModelBuilder builder, ApiVersion apiVersion, string routePrefix )
    {
        if ( apiVersion < ApiVersions.V3 )
        {
            return;
        }

        var order = builder.EntitySet<Order>( "Orders" ).EntityType.HasKey( o => o.Id );
        var lineItem = builder.EntityType<LineItem>().HasKey( li => li.Number );

        //if ( apiVersion < ApiVersions.V2 )
        //{
        //    order.Ignore( o => o.EffectiveDate );
        //    lineItem.Ignore( li => li.Fulfilled );
        //}

        //if ( apiVersion < ApiVersions.V3 )
        //{
        //    order.Ignore( o => o.Description );
        //}

        //if ( apiVersion == ApiVersions.V1 )
        //{
        //    order.Function( "MostExpensive" ).ReturnsFromEntitySet<Order>( "Orders" );
        //}

        //if ( apiVersion >= ApiVersions.V1 )
        //{
        //    order.Collection.Function( "MostExpensive" ).ReturnsFromEntitySet<Order>( "Orders" );
        //}

        //if ( apiVersion >= ApiVersions.V2 )
        //{
        //    order.Action( "Rate" ).Parameter<int>( "rating" );
        //}

    }`

**Comment by commonsensesoftware** [comment]
Similar issue as #821

**Comment by commonsensesoftware** [comment]
Long story short, this was a bug. If you're interested in the details, see #821.

_Preview 3_ is now available and contains the fix for this issue. I've also gone through all of the OData OpenAPI examples to verify that they should all work. 😉 Let me know if this resolves your issue.

**Comment by rgtek** [comment]
Thank you. It is now working correctly for me. Good job.
