### ISSUE TITLE
6.0 preview: unspecified API version when fetching by key

### ISSUE THREAD

**Issue by spaasis** [dotnet/aspnet-api-versioning#833]
One more before I go to bed for tonight - this might actually be a bug and not just me misconfiguring things 😅

In my controller I have:
```
namespace WebApi.V1.OData;

public class MyThingsController : BaseODataController {
    [EnableQuery]
    public async Task<SingleResult<MyOutput>> Get(Guid key) => SingleResult.Create(await Mediator.Send(new GetMyThing(key)));
```
And the Versioning is configured like:
```
    services.AddApiVersioning(o => o.ReportApiVersions = true)
        .AddMvc(o => o.Conventions.Add(new VersionByNamespaceConvention()))
        .AddOData(o => o.AddRouteComponents("api/v{version:apiVersion}/odata"))
        .AddODataApiExplorer(o => {
            o.GroupNameFormat = "'v'VVV";
            o.SubstituteApiVersionInUrl = true;
        })
        .AddApiExplorer(o => {
            o.GroupNameFormat = "'v'VVV";
            o.SubstituteApiVersionInUrl = true;
        });
```

Now calling `https://localhost:44395/api/v1/odata/MyThings(fc22c6c9-57eb-4368-bb0e-5a1d8a748fa6)` works but `https://localhost:44395/api/v1/odata/MyThings/fc22c6c9-57eb-4368-bb0e-5a1d8a748fa6` does not.
The latter reports a missing api version error:
```
{
	"type": "https//:docs.api-versioning.org#unspecified",
	"title": "Unspecified API version",
	"status": 400,
	"detail": "An API version is required, but was not specified.",
	"Code": "ApiVersionUnspecified",
	"traceId": "00-e35b7361f619c2e1b01971fb2ff2fb6a-32a4bdb017741012-00"
}
```

As per https://devblogs.microsoft.com/odata/routing-in-asp-net-core-8-0-preview/#endpoint-in-asp-net-core-odata I believe these both should work by default?

**Comment by commonsensesoftware** [comment]
There's a couple of possibilities:

1. Make sure/check the `options.RouteOptions` specified in `AddOData`. These are still honored and _may_ have an effect
2. Enable `app.UseODataRouteDebug()` and see what `~/$odata` shows. It's entirely possible that OData is not discovering the route. I ran into this issue many times myself and this was really useful. It's not very clear to when and why you have to add route templates for some scenarios, while others do not. Could be my misconfiguration or an issue with OData

**Comment by spaasis** [comment]
Thanks for the quick reply again :)

1) No such configs on this app so on to the next one
2) I had no idea about that config - that would have been (and will be) immensely helpful

Both versions of the endpoint are listed in the debug page so I guess the OData side is fine?
![image](https://user-images.githubusercontent.com/17126867/170358964-9d302d33-3f35-4dd5-b1cb-408b7727db6e.png)

**Comment by commonsensesoftware** [comment]
Cool. Yeah, Sam added that in OData 7 or 8. The matching of OData conventions is kind of black box when troubleshooting. It's a very welcomed addition. It really helped me iron out and verify many of the OData routes were being matched.

Strange. I'll see if I can repro this and find any additional details. It seems like it _should_ work to me.

>BTW: `AddODataApiExplorer` depends on `AddApiExplorer` so you don't have to set the options twice. They overlap. As soon as `AddODataApiExplorer` is added, it will replace the default options factory used by `AddApiExplorer` thereby using the same set of options. You shouldn't have to work _that_ hard 😉 .

**Comment by spaasis** [comment]
Alright, some further information:
- doing the same setup on the ODataOpenApiExample project works
  - both versions of the endpoint are shown in the Swagger UI whereas for my project only the one endpoint is listed
- when I configure `options.RouteOptions.EnableKeyInParenthesis = false;` to my project the `/things/{id}` shows up in SwaggerUI and it works fine


This is enough for me, since the /things/{id} is the format we actually want, but I am still curious as to why this happens.

My SwaggerDefaultValues are copied from the sample project, and surely swagger has nothing to do with this anyway...

I can't seem to spot anything else suspicious from my DI or configs and I tried to copy any differences I could think of to the sample but your stuff just keeps working 😅

**Comment by commonsensesoftware** [comment]
If you have a repro or at least a similar setup, that _might_ be enough. There _shouldn't_ be an issue for routing, but the API Explorer extensions clone descriptions and fan them out per API version. OData puts all matching selectors on a single action endpoint (that's not wrong and is arguably logical, but it's uncommon).

I do know that OData enables both _Key In Parenthesis_ and _Key in Segment_ by default. That's why I set up the OpenAPI example like that. This should also be apparent by looking at the `~/$odata` info. Of course, that's by convention. If you define the route template explicitly, then that's what's used.

**Comment by spaasis** [comment]
I tried hard to repro on the examples but couldn't get it to break. Since I got the behavior I needed with the options tweak I'm gonna close this so it doesn't haunt your issues list as I'm gonna be offline for a couple of weeks.
