### ISSUE TITLE
Failed to retrieve information about Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer

### ISSUE THREAD

**Issue by AlFalahTaieb** [dotnet/aspnet-api-versioning#842]
```
/usr/share/dotnet/sdk/5.0.408/NuGet.targets(131,5): error : Failed to retrieve information about 'Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer' from remote source 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.mvc.versioning.apiexplorer/index.json'. [/builds/dsi/sipp/sipp-apps/api/src/SIPPApi.sln]
/usr/share/dotnet/sdk/5.0.408/NuGet.targets(131,5): error :   The content at 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.mvc.versioning.apiexplorer/index.json' is not a valid JSON object. [/builds/dsi/sipp/sipp-apps/api/src/SIPPApi.sln]
/usr/share/dotnet/sdk/5.0.408/NuGet.targets(131,5): error :   The JSON document is not an object. [/builds/dsi/sipp/sipp-apps/api/src/SIPPApi.sln]
```

Got this problem today while deploying my pipeline, was working smoothly since months now, but i did not touch anything and today I'm facing this problem.
The problem is only related to `Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer`, I was able to retrieve the other packages with no issue.

Any help please ?

**Comment by commonsensesoftware** [comment]
Have you retried (recently)? I just downloaded and open the file just fine. It's definitely valid JSON. It can be further confirmed by simply opening the link/document in the browser.

https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.mvc.versioning.apiexplorer/index.json

This appears to be on a build server. If it's not transient, then the issue _could_ be related to a bad, cached result. The simplest explanation would be a partial, incomplete download of the document. Issues on www.nuget.org beyond a publishing snafu are outside my control. If a simple retry/rebuild on the server is not working, then I would try clearing or bypassing the NuGet cache as part of the build.

**Comment by commonsensesoftware** [comment]
This appears to have a been a transient issue that occurred on your build server. It's been a couple of months without an update, so I'm going to assume the issue has been resolved. If the issue somehow remains, I'm willing to reopen the issue and investigate further. Thanks.
