### ISSUE TITLE
Getting Microsoft.AspNetCore.OData.Versioning to work with Microsoft.AspNetCore.OData v8.0.11?

### ISSUE THREAD

**Issue by jwstemper** [dotnet/aspnet-api-versioning#882]
### Discussed in https://github.com/dotnet/aspnet-api-versioning/discussions/881

<div type='discussions-op-text'>

<sup>Originally posted by **jwstemper** September 29, 2022</sup>
The latest version of Microsoft.AspNetCore.OData.Versioning (5.0.0) specifics that it works with  Microsoft.AspNetCore.OData less than v8.  Is there something in the works to work with versions newer? i.e. 8.0.11?

Is there a preferred way to do versioning other than the Microsoft.AspNetCore.OData.Versioning library?</div>

**Comment by commonsensesoftware** [comment]
Per the discussion and `README.md`, the **Asp.Versioning.OData.*** packages support OData `8.x`.

**Comment by commonsensesoftware** [comment]
This issue/question has been answered and there doesn't appear to be any follow-up. I'm happy to discuss further if there are more questions. The referenced discussion is still open. 😉
