### ISSUE TITLE
Provide Documentation for 6.0 and Above

### ISSUE THREAD

**Issue by commonsensesoftware** [dotnet/aspnet-api-versioning#885]
Several breaking changes have been made since the `6.0` release. Although the code examples have been updated, the documentation (e.g. wiki) has not. The documentation should provide the up-to-date information.

**Comment by andyfurniss4** [comment]
Would approve of this. Just spent a while trying to figure out why various methods were not available to me when referring to the wiki.

**Comment by commonsensesoftware** [comment]
Sorry about that. Documentation is important, but as a one man show, I have limits. My top priority is making sure no one is blocked. The best reference is the example projects. They are always up to date.

**Comment by andyfurniss4** [comment]
No worries! I read the background so I understand your position and I know documentation is everyone's least favourite job! 😆

I will refer to the example projects from now on. Thank you!

**Comment by commonsensesoftware** [comment]
If you're following this issue or you stumbled across it, all of the documentation should now be up-to-date. There are even new topics such as the client-side extensions. If you find any errors or omissions, feel free to post them here or open a new issue.

Some time in the future, I may build out a fully-fledged documentation site. I'm even considering writing a book because I think there is enough content and details to do so. Creating some videos is on my bucket list this year. Stay tuned. 😉
