### ISSUE TITLE
Unable to disable default path templates

### ISSUE THREAD

**Issue by sindhuselvaraj** [dotnet/aspnet-api-versioning#892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an application that uses OData 8 with .net 7
For all the ODataControllers, the built-in routing conventions by default add additional path templates for Get, Put and Delete with no option to disable the $count, cast (model added) and Functions path templates.

![image](https://user-images.githubusercontent.com/16284614/195504121-56d2951a-0ec1-4675-8619-8ce58673437a.png)

![image](https://user-images.githubusercontent.com/16284614/195504553-03d82a82-1828-4ba9-85a9-47f90790cddc.png)

### Expected Behavior

Additional path templates should not be added by default or there should be an option to disable them like below

 options.RouteOptions.EnableKeyAsSegment = false;
 options.RouteOptions.EnableKeyInParenthesis = true;

### Steps To Reproduce

**Create a ODataController with below endpoints**

[HttpGet]
[EnableQuery]
public IActionResult GetDataSource()

[HttpGet]
[EnableQuery]
public async Task<IActionResult> GetDataSource(int key)

[HttpPost]
public async Task<IActionResult> PostDataSource([FromBody] DataSource)

[HttpDelete]
public async Task<IActionResult> DeleteDataSource(int key)

**ConfigureServices has below configuration**

 services.AddControllers()
      .AddOData(options => {
          options.EnableQueryFeatures();
          options.RouteOptions.EnableKeyAsSegment = false;
          options.RouteOptions.EnableKeyInParenthesis = true;
  });

### Exceptions (if any)

No exceptions

### .NET Version

7.0.100-preview.7.22377.5

**Comment by commonsensesoftware** [comment]
This appears to be more of an issue with what OData does versus anything specific to API Versioning. `EnableQueryFeatures()` will enable **all** query features at a global level, including `$count`.

I don't see any specific `cast` templates, but I think you are referring to the _qualified_ versus _unqualified_ route templates for _operations_ (e.g. a _function_ or _action_). These can be controlled with:

```c#
options.RouteOptions.EnableQualifiedOperationCall = false;
options.RouteOptions.EnableUnqualifiedOperationCall = true;
```

OData generates all of the route templates. API Versioning is no longer involved with any part of their generation. If you want to see what OData is generating as well as what it thinks is or isn't an OData route, enable the `app.UseODataRouteDebug()` middleware (usually high in the order). Then run the app and navigate to `~/$odata`. This will display a simple HTML page with all OData and non-OData route templates.

**Comment by sindhuselvaraj** [comment]
Thanks. Will take it up with the OData team
