### ISSUE TITLE
URI version in path 

### ISSUE THREAD

**Issue by MarlonSchuetz** [dotnet/aspnet-api-versioning#902]
Openapi 3x will change sometimes definitions, for exemple, base path to server. Usually URI version stay in path on swagger.json, but I need drop version of path and move to server.url
[swagger 3.0](https://swagger.io/docs/specification/api-host-and-base-path/)
Expected:
![image](https://user-images.githubusercontent.com/11525336/200836653-09b31d44-69a4-4d20-a4bb-119fdaf4f7f0.png)
Common implementation:
![image](https://user-images.githubusercontent.com/11525336/200837483-b667a69b-5764-46ca-b07c-8b30a8b2e54b.png)

**Comment by commonsensesoftware** [comment]
I'm not 100% sure I follow. It would seem you want the `paths` to be relative to some base path - namely `/api/v3`? This would be a product of whatever OpenAPI generator you use (Swashbuckle?). API Versioning itself doesn't have any direct connection to OpenAPI. Addition information is provided via the API Explorer, but it's up to the OpenAPI side to use it.

**Comment by MarlonSchuetz** [comment]
I'm using Swashbuckle. Probably this question must be redirected to the Swashbuckle project, already that API Versioning doesn't have a connection to OpenAPI.

**Comment by commonsensesoftware** [comment]
Without more information, that seems to be the case. The API Explorer extensions will provide the API descriptions used by Swashbuckle/OpenAPI, but that's the end of things. How the document is produced is up to the OpenAPI generator - like Swashbuckle.

**Comment by commonsensesoftware** [comment]
It seems we reached this conclusion of this issue that the crux of the problem is external. If there's more to this issue or there is a problem specific to integration with API Versioning, feel free to post more information or reopen the issue.
