### ISSUE TITLE
Header Versioning in .NET 6

### ISSUE THREAD

**Issue by magna-nz** [dotnet/aspnet-api-versioning#903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hi

Alot of the sample apps seem to be out of date as well as the documentation.

How can we do Header Versioning in .NET 6.0 with this package?

Can't see any samples or find any documentation.

### Describe the solution you'd like

Documenation on header versioning in .net  6

**Comment by commonsensesoftware** [comment]
All of the examples should be current. If you have found something, feel free to call it out and I'll get it updated.  Documentation is a bit out of date, but that is primarily related to new features. I'm tracking that as a separate issue and hope to overhaul the entire wiki.

To answer your question - yes - you can version by HTTP header. This is documented under [header versioning](../wiki/Versioning-by-Header). The setup is as simple as:

```c#
options => options.ApiVersionReader = new HeaderApiVersionReader("x-ms-version");
```

You can use any header you like, even more than one.

You can version your API the following ways:

- By media type (`MediaTypeApiVersionReader` or `MediaTypeApiVersionReaderBuilder`)
- By query string (`QueryStringApiVersionReader`; default)
- By header (`HeaderApiVersionReader`)
- By URL segment (`UrlSegmentApiVersionReader`)
- Any custom `IApiVersionReader`
- Any combination of composed readers (`ApiVersionReader.Combine`)

**Comment by commonsensesoftware** [comment]
This question has been answered and seems to have reached its logical conclusion. If you have more questions, feel free to ask. To elaborate on the full configuration in .NET 6+, it should be:

```c#
builder.Services
       .AddApiVersioning() // ← Minimal API support (new core); configure options.ApiVersionReader  here
       .AddMvc();          // ← Add MVC Core (this is different from IServicesCollection.AddMvc)
```
