### ISSUE TITLE
Integration Api version with route parameter and swagger

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/aspnet-api-versioning#909]
Hi,
I want to integrate swagger with API versioning in route parameter minimal API, something like: `api/v{version:apiVersion}/catalogs`.
Do you have any sample code?

**Comment by commonsensesoftware** [comment]
Yes. It looks like this:

https://github.com/dotnet/aspnet-api-versioning/blob/88323136a97a59fcee24517a514c1a445530c7e2/examples/AspNetCore/WebApi/MinimalOpenApiExample/Program.cs#L159

**Comment by mehdihadeli** [comment]
@commonsensesoftware It works, thanks :)
Is it possible to set version on swagger UI manually and set version route parameter based on that, for example inner a text box?

**Comment by commonsensesoftware** [comment]
I believe you are asking if you can make:

`/api/v{version:apiVersion}/people/{id:int}`

into

`/api/v`/people/{id}`

Yes, you can. 😉 

```c#
builder.Services
       .AddApiVersioning( options => options.ApiVersionReader = new UrlSegmentApiVersionReader() )
       .AddApiExplorer( options => options.SubstitutueApiVersionInUrl = true );
```

The default reader is `ApiVersionReader.Combine(new QueryStringApiVersionReader(), new UrlSegmentApiVersionReader())` to cover most user scenarios. This can be undesirable for OpenAPI. Substituting the corresponding API version in the route template removes the parameter and token placeholder.

**Comment by mehdihadeli** [comment]
@commonsensesoftware 
Yes exactly, when I set `SubstitutueApiVersionInUrl=true` swagger UI infer versions in UI automatically and when I set `SubstitutueApiVersionInUrl=false` I can set version for specific API manually in swagger UI
