### ISSUE TITLE
[OData] EDM is changed to have camelCase members

### ISSUE THREAD

**Issue by dnperfors** [dotnet/aspnet-api-versioning#912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In our project we have been looking into the casing of several properties of our model and how they end up in Swagger. What we noticed is that, no matter how hard you try, the member names of an EDM are always changed to camelCase.
My example repository at: https://github.com/dnperfors/eLibrary shows it nicely.

The EDM without API Versioning:
```xml
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
  <edmx:DataServices>
    <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="eLibrary.WebApi.OData.Models">
      <EntityType Name="Book">
        <Key>
          <PropertyRef Name="Id"/>
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false"/>
        <Property Name="Title" Type="Edm.String" Nullable="false"/>
        <Property Name="Author" Type="Edm.String" Nullable="false"/>
      </EntityType>
    </Schema>
    <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Default">
      <EntityContainer Name="Container">
        <EntitySet Name="Books" EntityType="eLibrary.WebApi.OData.Models.Book"/>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
```

EDM with Api Versioning:
``` xml
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
  <edmx:DataServices>
    <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="eLibrary.WebApi.OData.Models">
      <EntityType Name="Book">
        <Key>
          <PropertyRef Name="id"/>
        </Key>
        <Property Name="id" Type="Edm.Int32" Nullable="false"/>
        <Property Name="title" Type="Edm.String" Nullable="false"/>
        <Property Name="author" Type="Edm.String" Nullable="false"/>
      </EntityType>
    </Schema>
    <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Default">
      <EntityContainer Name="Container">
        <EntitySet Name="Books" EntityType="eLibrary.WebApi.OData.Models.Book"/>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
```

### Expected Behavior

The EDM should have the default casing of OData.

### Steps To Reproduce

See my repository: https://github.com/dnperfors/eLibrary

**Comment by commonsensesoftware** [comment]
There's never a perfect solution for everyone. JSON is commonplace enough that most (but not all) prefer and expect the wire payload to conform to the accepted JSON naming conventions, which is Camelcase. This also provides greater parity for people that combine OData and vanilla ASP.NET Core APIs.

Although Camelcase is the default, it's easy to change:

```c#
builder.Services
       .AddApiVersioning()
       .AddOData( options =>
        {
          options.AddRouteComponents();

          // the default setup is:
          // options.ModelBuilder.ModelBuilderFactory = () => new ODataConventionModelBuilder().EnableLowerCamelCase();

          options.ModelBuilder.ModelBuilderFactory = () => new ODataConventionModelBuilder();
        } );
```

I hope that helps.

**Comment by dnperfors** [comment]
Thanks, that totally helps, somehow I missed that option :)

And although I understand the reasoning, in this case I don't totally agree, since the naming convention for JSON should be done by the serializer  when creating the response and not when creating the EDM. That being said, I wouldn't be surprised that it wasn't possible and changing this behavior now would be a breaking change.

In our case, we actually want to have the urls like `/Books(1)/Authors`, but in JSON we want the field `authors` (since that is the default), but now I am writing this, I am actually beginning to doubt and would rather like my urls in lowercase, which makes more sense to me...

All those options 😆 

(Closing the issue, since it is actually resolved, since you already provided the possibility to change the overridden default behavior 😉)

**Comment by commonsensesoftware** [comment]
You're not wrong nor do I disagree. OData, unfortunately, puts some coupling around what the EDM defines versus CLR types versus serialization (like JSON). If you supported XML and JSON, you'd want XML in Pascalcase, but JSON in Camelcase. I don't think the OData libraries have any support for that (it's an implementation problem vs protocol).

The casing of URLs is mixed too. The options will certainly influence the default names, but there are OData-specific options for whether they are case-sensitive or not. I don't remember how off the top of my head, but I seem to recall there is a way to force OData to use all lowercase if you want. I know URL matching is now case-insensitive by default. Too many people get snagged by that.  By spec, URLs are _supposed_ the case-sensitive. You have may have even run into that problem with certain web servers (I know I have). In practice, that doesn't, make a whole lot of sense IMHO. There shouldn't be any universe where `/Books(1)` means something different from `/books(1)`.

**Comment by dnperfors** [comment]
Totally agree, I saw several options in OData where the casing is ignored, which is a good thing, but now I only have to make sure the defaults for the entitysets are actual lowercase, but since those are controlled by humans in the EDM, that shouldn't be a problem :)

**Comment by mdsharpe** [comment]
Just lost several hours to this, trying to figure out why my models were not materializing in Microsoft.OData.Client.

The client appears to have zero tolerance for property name casing differences.

Very surprised that merely adding _versioning_ to my OData API would break its compatibility with Microsoft's client library.

I know this is an old issue, but I would suggest that this library shouldn't change this behavior by default :-)

**Comment by commonsensesoftware** [comment]
@mdsharpe This issue is, unfortunately, a double-edge sword depending on the direction you're coming from. Devs coming from vanilla controllers or _Minimal APIs_ are surprised that the default is Pascalcase/Titlecase. They hit a wall trying to configure the case settings through the standard JSON settings, which have no effect on the OData configuration. I've seen OData devs struggle on that too. This inconsistency is a significant gap and miss on the OData team's part IMHO.

My original stance was to not touch anything. These are knobs that you should choose to turn. After years of watching devs either set the default to Camelcase or struggle with the casing incongruence, I decided to opt to normalize everything to Camelcase, which is the de facto standard for JSON, even if that's not what OData defaults to.

OData 8+ did provide the configuration option `EnableCaseInsensitive` on the builder. I would be open to setting this as the default to avoid the casing landmine. It won't be as performant, but I would prefer for the 80% to fall into the pit of success and the 20% who need maximum performance to dive deep and tune options the way they need them. I'll add this to my list for the next release, but feel free to create a new issue to make that the default.

**Comment by mdsharpe** [comment]
@commonsensesoftware Thanks so much for getting back to me, that's really made my day!

I understand your stance, and frankly I too would normally expect pascal case everywhere. OData is weird in that regard.

I will look into `EnableCaseInsensitive`, as although I spotted that during my adventures yesterday, I was under the impression it was focused on URLs not property names. Thanks!!
