### ISSUE TITLE
Issue updating from 5.0.0 to 6+

### ISSUE THREAD

**Issue by oifrah** [dotnet/aspnet-api-versioning#921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It's probably not a bug or feature request but we encounter difficulties updating the package.

We didn't find any kind of migration guide - That's why I opened as feature request.

We updated from version 5 to version 6.0.1 as part of an update to .net6. 

We managed to do most of the crossover to the new version but there is 1 thing we still cannot seem to find how to do.
We we’re using the function MapVersionedODataRoute like so:
![image](https://user-images.githubusercontent.com/105144682/203033018-0e593e14-9511-4210-a399-970a3eb0dabe.png)

And we can’t seem to find how to recreate this.

What we found was something to do with AddRouteComponents, along the lines of:
![image](https://user-images.githubusercontent.com/105144682/203033106-4c9b489f-9558-4958-8570-2fb5bd7070ad.png)

but this code is called from the ConfigureServices function that does not have access to the model builder that we need for the EDM model, as opposed to the old code that ran in the Configure function and did have access to it. Our EDM model is complicated and is edited in many places so the examples of creating a GetEdmModel function in the same file that creats the model is not a possibility for us at this time. We need some way to access the model that is created elsewhere, like the old version. 

Any change you can point me to somewhere that will help us solve this?

Thanks

### Describe the solution you'd like

Direction about the changes need to be made or a guide about changes need to be done for the upgrade

**Comment by commonsensesoftware** [comment]
Good question. The common configuration is still expected to be through `IModelConfiguration`, but - just as before - you don't _have_ to use them. The `VersionedODataModelBuilder` is still a service registered in the container, but it's less obvious where you would retrieve it can continue to configuration. This is now accessible via `ODataApiVersioningOptions.ModelBuilder`:

```c#
// add OData services and global configuration
// note: AddRouteComponents here will be ignored
builder.Services
       .AddControllers()
       .AddOData( options => options.UrlKeyDelimiter = ODataUrlKeyDelimiter.Parentheses );

builder.Services
       .AddApiVersioning()
       .AddOData( options =>
        {
           // options.ModelBuilder.GetEdmModels() would be equivalent, but there is intentionally
           // no way to pass down the EDM models because it's not necessary. if you need to further
           // configure the EDM, the simplest approach is to use the post-creation callback that has
           // always been there
           options.ModelBuilder.OnModelCreated = ( builder, edm ) =>
           {
               // this will be called once for each non-empty EDM per API version
           };

           // you MUST register version-specific OData routes here. the OData team didn't take
           // any of my feedback to make their design extensible, which ultimately led down a
           // a path where I had to reimplement parts of the setup because it's impossible to get
           // in front or change what OData does by default. I kept many names and setup similar
           // to the built-in OData method so that it feels familiar to an OData user
           options.AddRouteComponents( "{projectName}/odata/v{version:apiVersion}" );
        } );
```

I suspect that should cover most scenarios, but if you really need to get in front of creating the EDMs, then you would have to extend `VersionedODataModelBuilder`, override `GetEdmModels`, and replace it the DI container.

I have an issue tracking the lack for documentation for some of the 6.0+ changes that I hope I'll be able to tackle in the near future. This affects OData the most because OData 8.0+ itself is quite different.

**Comment by commonsensesoftware** [comment]
Which paths? Do you have a repro? You've only shared fragments of the configuration, which makes it difficult to troubleshoot. You should be able to find which path is incorrect from the error to give you a clue. The [OData OpenAPI example](../blob/9e43aa44531ced7c28b939f96f831b3e3fa60eee/examples/AspNetCore/OData/ODataOpenApiExample/Program.cs) provides an end-to-end example of how to set combine all of the pieces together.

**Comment by commonsensesoftware** [comment]
Checking in one more time. Were you able to resolve your issue?

**Comment by oifrah** [comment]
No 😊,

We wanted to dig more and provide more information,

First - We encounter kind of duplications in the models and the API descriptions.
Let's start with our dependencies:
```
<ItemGroup>
  <PackageReference Include="Asp.Versioning.OData.ApiExplorer" Version="6.1.0" />
  <PackageReference Include="LinqKit.Core" Version="1.2.2" />
  <PackageReference Include="Microsoft.AspNet.OData" Version="7.6.3" />
  <PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="2.2.0" />
  <PackageReference Include="LaaS.ServiceFabric.Configuration" Version="1.0.4" />
  <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.20.0" />
  <PackageReference Include="Microsoft.ApplicationInsights.ServiceFabric" Version="2.3.1" />
  <PackageReference Include="Microsoft.ApplicationInsights.ServiceFabric.Native" Version="2.3.1" />
  <PackageReference Include="Microsoft.ApplicationInsights.SnapshotCollector" Version="1.3.7.5" />
  <PackageReference Include="Microsoft.AspNetCore.OData" Version="8.0.11" />
  <PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="2.2.0" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.14" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.14">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  </PackageReference>
  <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="5.0.1" />
  <PackageReference Include="Microsoft.ServiceFabric" Version="7.2.445" />
  <PackageReference Include="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="4.2.445" />
  <PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="4.2.445" />
  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  <PackageReference Include="ProjectServiceGateway" Version="1.1.20" />
  <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="5.6.3" />
</ItemGroup>
```

In order to make swagger work we needed to use the ```c.CustomSchemaIds(type => type.FullName + type.GetHashCode());```
![image](https://user-images.githubusercontent.com/105144682/212674839-a50f9c1d-a26a-44dc-9e76-75a28b80dcb8.png)

After that it loads but we see the dups..
![image](https://user-images.githubusercontent.com/105144682/212674472-2f38d889-ca01-43ca-a91d-f57f4760bfce.png)
and
![image](https://user-images.githubusercontent.com/105144682/212674551-445fd065-1a5f-4cf6-82dc-781533e9b29e.png)
(This is just part of the app - we have multiple APIs and models)

We have an odataController which all the controllers inherits from:
```
using System.Linq;
using DataSearch.Common.Authorization;
using DataSearch.Contexts;
using DataSearch.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.OData.Routing.Controllers;
using Microsoft.AspNetCore.OData.Query;

 

namespace DataSearch.WebApi.V1
{
    [Produces("application/json")]
    public class ODataController<T> : ODataController where T : class, IHaveProjectName
    {
        protected readonly DataSearchContext Context;

 

        protected ODataController(DataSearchContext context)
        {
            Context = context;
        }

 

        [HttpGet]
        [Authorize(Role.Reader)]
        [EnableQuery(MaxExpansionDepth = 4, MaxNodeCount = 1000)]
        public virtual IQueryable<T> Get()
        {
            Context.GlobalSearchMode = false;
            var res = Context.Set<T>().AsNoTracking();
            return res;
        }
    }
}
```

Do you have any idea about the duplications and the $count?

Thanks for checking if it was resolved

**Comment by commonsensesoftware** [comment]
The first issue I see is that you're referencing**Microsoft.AspNet.OData** (`7.6.3`). That package is for ASP.NET Web API. You should be getting warnings from NuGet about that package. I suspect no part of it is actually used, but it shouldn't be there nevertheless.

There should be no need to use `CustomSchemaIds`. It's possible that your OData routes are incorrect. I recommend adding:

```c#
if ( app.Environment.IsDevelopment() )
{
    app.UseODataRouteDebug();
}
```

And then you can navigate to `~/$odata`. That will show the OData route table. If you see a route listed as non-OData, then you know the configuration is incorrect. I've run into that many times.

I don't have a lot more to go one. Sharing the relevant configuration might be helpful. A simple, stripped down repro would be best. Let's start with that.

**Comment by oifrah** [comment]
This is sample of the Odata Route table
![image](https://user-images.githubusercontent.com/105144682/215498552-24776cd2-d76f-4bd2-a956-c80078e5283b.png)

Also ...
I've used the AssemblyQualifiedName and it looks weird - 2 schemas for each model
![image](https://user-images.githubusercontent.com/105144682/215499513-ce7ad963-a82f-4c15-bb15-3aea065a4a06.png)

By looking on those images any chance you can point me why it can happens ?

Those dups started only after updating the packages and minor changes in the code.

**Comment by oifrah** [comment]
Maybe the model configuration file will give a clue ...
```
using System;
using System.Linq.Expressions;
using DataSearch.Models;
using Asp.Versioning.OData;
using Microsoft.OData.ModelBuilder;
using Asp.Versioning;

namespace DataSearch.Contexts
{
    public class ModelAllConfigurations : IModelConfiguration
    {
        public void Apply(ODataModelBuilder builder, ApiVersion apiVersion, string routePrefix = null)
        {
            if (apiVersion != new ApiVersion(1,0))
            {
                return;
            }

            builder
                .AddEntityWithOptions<Bucket>()
                .AddEntityWithOptions<Activity>();
        }
    }

    public static class ODataModelBuilderExtensions
    {
        public static ODataModelBuilder AddEntityWithOptions<T>(this ODataModelBuilder builder, Expression<Func<T, dynamic>> keyDefinitionExpression = null, string nameOverride = null) where T : class
        {
            var name = string.IsNullOrEmpty(nameOverride) ? typeof(T).Name : nameOverride;
            var entityTypeConfiguration = builder.EntitySet<T>(name)
                .EntityType;
            if (keyDefinitionExpression != null)
            {
                try
                {
                    entityTypeConfiguration.HasKey(keyDefinitionExpression);
                }
                catch (Exception)
                {
                    Console.WriteLine($"Entity Name: {name}");
                    throw;
                }
            }

            entityTypeConfiguration
                .Filter() // Allow for the $filter Command
                .Count() // Allow for the $count Command
                .Expand(4) // Allow for the $expand Command
                .OrderBy() // Allow for the $orderby Command
                .Page() // Allow for the $top and $skip Commands
                .Select(); // Allow for the $select Command
            return builder;
        }
    }
}
```

When I comment the whole class I get just the models without the `V_<version>_<guid>.DynamicModels` and the  options.ModelBuilder.OnModelCreated = (builder, edm) => {} is **not called**

We also using entity framework if it has any connection...

So I didn't catch if what I need is those with the V_<version> or the others...

Sorry for the amount of questions ... trying to figure it out because before we changed to .net 6 and updating the nuggets it worked well
Thanks!

**Comment by commonsensesoftware** [comment]
This _looks_ right, but something still seems to be missing. The model should only be substituted if the specific type doesn't match the EDM. This usually happens by applying `.Ignore` which I don't see. The other thing that is strange is that your configuration only applies if the API version is `1.0`. That is allowed, but then it should be impossible to get multiple models. The only other possibility is that have different configurations for API version **and** route prefix. This was implied by the route templates I saw above. I haven't tried mixing different EDMs with the same entity shape. If the same type, and hence name, are useful from multiple sources in the same API version that will always be a problem for OpenAPI. The names in the schema have to be unique. If they are exactly the same name and configuration, in theory, that should work, but I've never tried such a combination.

What does the configuration for

```c#
builder.Services.AddControllers().AddOData();
```

and 

```c#
builder.Services.AddApiVersioning().AddOData();
```

look like? I'll be surprised if there isn't any issue there.

You also still didn't mention how you are using annotations or if it's just referenced. Any other source of API Explorer information or input to Swashbuckle has the potential to provide incorrect or overriding information.

**Comment by oifrah** [comment]
```
            services.AddControllers(options =>
            {
                options.InputFormatters.RemoveType<XmlSerializerInputFormatter>();
                AddFilters(options, filterTypes);
            })
            .AddOData(options => 
            {
                options.UrlKeyDelimiter = ODataUrlKeyDelimiter.Parentheses;
            })
            .AddJsonOptions(opt =>
            {
                opt.JsonSerializerOptions.PropertyNamingPolicy = null;
                opt.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
                opt.JsonSerializerOptions.IgnoreNullValues = true;
            });
            services.AddApiVersioning(options => options.ReportApiVersions = true)
            .AddOData(options =>
            {
                options.ModelBuilder.OnModelCreated = (builder, edm) =>
                {
                    // this will be called once for each non-empty EDM per API version
                    var aaa = 1;
                };
                options.AddRouteComponents("{projectName}/odata/v{version:apiVersion}");
            })
            .AddODataApiExplorer(options =>
            {
                // add the versioned api explorer, which also adds IApiVersionDescriptionProvider service
                // note: the specified format code will format the version as "'v'major[.minor][-status]"
                options.GroupNameFormat = "'v'VVV";

                // note: this option is only necessary when versioning by url segment. the SubstitutionFormat
                // can also be used to control the format of the API version in route templates
                options.SubstituteApiVersionInUrl = true;

            });
```

**Comment by oifrah** [comment]
Good news 😊

I found that there was two controllers which had [Route("something")] - We did it because there was OdataRoutePrefix before
When I removed those attributes the duplicates disappeared

hope this issue will help someone in the future 

Thanks a lot.

We just stayed with the $count routed which we eliminated somewhere in the process of the initialization
