### ISSUE TITLE
Cannot set conventions in Asp.Versioning.Mvc

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnet-api-versioning#929]
---
**Issue moved from dotnet/aspnetcore#45384**
- Please respond to @sqlop.

---

_From @sqlop on Thursday, December 1, 2022 8:33:20 AM_

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello, 
I have used an old version library (Microsoft.AspNetCore.Mvc.Versioning 5.0.0). I want to migrate to Asp.Versioning.Mvc but I have a problem with Conventions.
Cannot set convention as before 
![image](https://user-images.githubusercontent.com/31932723/205003972-240ae3aa-fdb7-43ed-aac4-cd2400290e5b.png)

It seems there is no list of conventions in options anymore.
How can I set up conventions in the new library?

I have installed 
- "Asp.Versioning.Mvc" Version="6.3.1"
- "Asp.Versioning.Mvc.ApiExplorer" Version="6.3.1" 

### .NET Version

6.0.302

**Comment by commonsensesoftware** [comment]
@sqlop, it seems like you got what you needed so I'm going to close this out. If you're still stuck or have additional questions, feel free to reopen the issue or create a new one. Thanks.
