### ISSUE TITLE
Failed to customize the field name of the type

### ISSUE THREAD

**Issue by huanghaiqingit** [dotnet/aspnet-api-versioning#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://user-images.githubusercontent.com/103879245/210511096-1e2137ff-b9ab-46ef-8aa7-eee032510d27.png)

**Comment by commonsensesoftware** [comment]
I'm afraid I will need some additional details and context. This looks like it _might_ be related to OpenAPI, but it's hard to tell. I don't see how this is related to API Versioning. Can you share some more details?

**Comment by commonsensesoftware** [comment]
This issue has gone idle for nearly 2 months without a follow-up or elaboration as to the issue. I presume that the issue was solved or abandoned. If you're still having an issue provide additional detail and I'll be happy to help solve the problem. Thanks.
