### ISSUE TITLE
Bug in asp.net example

### ISSUE THREAD

**Issue by martinRocks** [dotnet/aspnet-api-versioning#950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to use this library in an dot.net framework 4.8 project and I can't get it to compile.  I have made a solution with the basic example from this git repo, a framework 4.8 example and a dot net 6 example.  The dot net 6 example works perfectly.  Please tell me what I'm missing?
[WebApiVersioning.zip](https://github.com/dotnet/aspnet-api-versioning/files/10395009/WebApiVersioning.zip)

### Expected Behavior

I'm expecting the code to compile and to work like the dot net 6 example in the attached solution.

**Comment by martinRocks** [comment]
Thank you so very much for the quick response.

Everything complies now, but I'm still missing something because in the framework 4.8 project, I'm getting the error "Multiple actions were found that match the request".  I making the request like this: curl -X GET 'http://localhost:61317/api/weatherforecast' -H 'Accept: application/json;version=1.0'

Here is my updated solution.
[WebApiVersioning.zip](https://github.com/dotnet/aspnet-api-versioning/files/10402969/WebApiVersioning.zip)

**Comment by commonsensesoftware** [comment]
The issue now is that you copied the OWIN self-host startup, but the application is configured to use IIS. Whatever is in `Startup.cs` is not being executed. What is executing is `Global.asax.cs`, which in turn calls `WebApiConfig.Register`. Inspecting that appears to calls the standard Web API template setup without any API versioning configuration. As currently configured, this would naturally result in duplicate, ambiguous routes.

First change `WebApiConfig.Register` to:

```c#
public static void Register(HttpConfiguration config)
{
    config.AddApiVersioning(options =>
    {
        options.ReportApiVersions = true;
        options.AssumeDefaultVersionWhenUnspecified = true;
        options.DefaultApiVersion = new ApiVersion(1, 0); // this is already the default BTW
        options.ApiVersionReader = new MediaTypeApiVersionReader("version");
    });

    config.MapHttpAttributeRoutes();
}
```

Personally, I'm not a fan of convention-based routing. It find it harder to reason about. Direct routing (aka attribute-routing) is easier to follow and has better parity with ASP.NET Core. I'm not showing it here, but it's supported if you really want to use it. I recommend choosing one style or the other. Mixing styles will make you go cross-eyed.

 You now need to update the controller:

```c#
[ApiVersion(1.0)]
[ApiVersion(2.0)]
[RoutePrefix("api/weatherforecast")]
public class WeatherForecastController : ApiController
{
    [Route]
    [HttpGet, MapToApiVersion(1.0)]
    public IEnumerable<VmWeatherForecast> Get() => Ok(Enumerable.Empty<VmWeatherForecast>());

    [Route]
    [HttpGet, MapToApiVersion(2.0)]
    public IEnumerable<VmWeatherForecast> GetV2() => Ok(Enumerable.Empty<VmWeatherForecast>());
}
```

You should now see:

- `curl -X GET 'http://localhost:61317/api/weatherforecast' -H 'Accept: application/json;version=1.0'`
- `curl -X GET 'http://localhost:61317/api/weatherforecast' -H 'Accept: application/json;version=2.0'`

Work as expected.

**Comment by martinRocks** [comment]
Thank you again.  I think this solves all my problems and you have a great library.  By the way, I removed my startup.cs and the Microsoft.AspNet.WebApi.OwinSelfHost package.  I don't know if I will need to put that back in, but so far everything is working.  

Thank you so very much.

**Comment by commonsensesoftware** [comment]
If you're hosting on IIS with `System.Web`, that shouldn't be needed. If you want to use the OWIN-style startup (aka project _Katana_), there is a different package for hosting on IIS (instead of self-host). It shouldn't matter a whole lot which way you go.  _Project Katana_ was the inspiration for ASP.NET Core `1.0` and the OWIN-style will have a similar setup. This is likely only interesting if you ever plan to port/convert the project ASP.NET Core.
