### ISSUE TITLE
MediaTypeApiVersionReader doesn't resolve controller ambiguity

### ISSUE THREAD

**Issue by bhood-zorus** [dotnet/aspnet-api-versioning#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In a brand new API project, using `MediaTypeApiVersionReader` [as prescribed by the wiki](https://github.com/dotnet/aspnet-api-versioning/wiki/Versioning-by-Media-Type) doesn't work. I have tried both .NET 6 and 7 (package versions 6.4.0 and 7.0.0 respectively). I have tried both a plainly constructed reader as well as used the builder.

I have looked around for other issues to see whether I'm maybe misusing it. #338 looks close, but after reviewing the comments I don't think I'm breaking any of the rules. 

The 2.0 POST route _does_ resolve.

### Expected Behavior

The API correctly resolves the ambiguity between the two controllers based on the specified version.

### Steps To Reproduce

Repo: [Here](https://github.com/bhood-zorus/MediaTypeApiVersionReaderDemo/)

Run the demo project and send a request with a single header `Accept` whose value is `application/json;v=2`.

Powershell:
```
PS C:\Users\bhood> $headers = @{ 'Accept' = 'application/json;v=2' }
PS C:\Users\bhood> iwr -Uri "https://localhost:7165/api/helloworld" -Headers $headers
```

### Exceptions (if any)

```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:

Services.V2.HelloWorldController.Get (VersioningDemo)
Services.V1.HelloWorldController.Get (VersioningDemo)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json; v=2
Host: localhost:7165
User-Agent: Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19045; en-US) PowerShell/7.3.2
```

### .NET Version

7.0.102

**Comment by commonsensesoftware** [comment]
I don't think this is related to the `MediaTypeApiVersionReader` specifically; however, there is clearly something amiss. What do you have for your configuration setup? Just the API Versioning configuration should be sufficient.
