### ISSUE TITLE
OData navigation routing and property routing not working when using versioning with convention based routing 

### ISSUE THREAD

**Issue by cjwainwright** [dotnet/aspnet-api-versioning#962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using convention based routing in odata it should be possible to set up actions for "property routing" and "navigation routing", e.g. in the following controller, the last two actions are examples of these.
```c#
[ApiVersion(1)]
public class PeopleController : ODataController
{
    // e.g. ~/people
    public IActionResult Get()
    {
        return Ok(new List<Person>());
    }

    // e.g. ~/people/1
    public IActionResult Get(int key)
    {
        return Ok(new Person() { Id = key, Name = "X" });
    }

    // e.g. ~/people/1/name
    public IActionResult GetName(int key)
    {
        return Ok("X");
    }

    // e.g. ~/people/1/children
    public IActionResult GetChildren(int key)
    {
        return Ok(new List<Child>());
    }
}
```
When configuring OData using the non-versioned approach, this all works as expected, i.e. using the following setup:
```c#
var modelBuilder = new ODataConventionModelBuilder();
modelBuilder.EntitySet<Person>("People");
builder.Services.AddControllers().AddOData(options =>
{
    options.AddRouteComponents(modelBuilder.GetEdmModel());
});
```
I can then visit `~/people/1/name` and `~/people/1/children` and get the expected results.

However when I configure odata to use versioning the last two routes are not discovered, i.e. using the following setup:
```c#
builder.Services.AddControllers().AddOData();
builder.Services.AddApiVersioning().AddOData(options =>
{
    options.ModelBuilder.DefaultModelConfiguration = (builder, version, prefix) =>
    {
        builder.EntitySet<Person>("People");
    };
    options.AddRouteComponents();
});
```
If I visit `~/people/1/name` or `~/people/1/children` I get 404 errors.

The only routes that show on route debugging are the first two:
![image](https://user-images.githubusercontent.com/1623948/219437051-a2bd7d49-aafa-4963-b864-e6875213263f.png)

### Expected Behavior

All convention based routing should work the same way as if set up without versioning. "Property routing" such as `~/people/1/name` and "Navigation routing" such as `~/people/1/children` should work as expected.

### Steps To Reproduce

Repo with repro is here:

https://github.com/cjwainwright/AspVersioningODataConventionRoutingBug

Simply switch the value of the #if preprocessor directive to toggle between the versioned and non-versioned setup in Program.cs and visit https://localhost:7009/$odata to see the difference in routes that are recognized.

### .NET Version

.NET 6

### Anything else?

ASP.NET Core 6
Visual Studio 2022

**Comment by cjwainwright** [comment]
@commonsensesoftware Thanks very much for the detail response, yes both options seem to fix the issue for me. There's no way I would've been able to work that out. I didn't see this anywhere in the docs or examples, wonder if this should be documented somehow, assuming it's not straightforward to change the behaviour of the default configuration?

**Comment by commonsensesoftware** [comment]
These quirks are certainly annoying. I wish there was more I could do about it. I'm not sure I can. I find the incongruency in OData configuration infuriating at times.

Consider this issue as an example. Regardless of whether you use the default or:

```c#
options.ModelBuilder.ModelBuilderFactory = () => new ODataConventionModelBuilder();
```

The routing to the controller and matching the entity set is case-insensitive. For example, all of the following work whether you use Camelcase or the default Pascalcase:

- `/People?api-version=1.0`
- `/People/1?api-version=1.0`
- `/people?api-version=1.0`
- `/people/1?api-version=1.0`

Interestingly, this works regardless of whether you configure case-insensitivity for controllers with:

```c#
builder.Services.AddControllers().AddOData(options => options.RouteOptions.EnableControllerNameCaseInsensitive = true);
```

The default is `false`, but it works either way. I understand the bug that missed the case for properties, but it _only_ works in the later versions if you configure `EnablePropertyNameCaseInsensitive = true` 😖. In my opinion, I'm not even sure the casing should ever matter. If we wanted to squeeze every last bit of performance, then - sure - there could be one setting that indicates if matches are case-sensitive or case-insensitive. No one will have some parts in one case and other parts in other cases in my experience.

Dealing with these idiosyncrasies in OData are just as frustrating for me as they are for users. I don't have good answers and documenting/re-documenting OData is not sustainable for me. That's something the OData team _should_ be doing. I do try to incorporate some of these learnings in issues and the example projects to showcase _real world_ configurations. I don't believe I have specific examples for property navigations, so I'll definitely add this setting to the examples in the next set of changes. I do call out the default configuration in the [Model Builder Factory](../wiki/Versioned-ODataModelBuilder#model-builder-factory), but after that, the expectation is that a developer would be familiar with using OData. That was clearly the miss that resulted in this issue, but beyond that, the same issue would have arisen if `EnableLowerCamelCase` would have been used.

If you have other suggestions on how to improve the experience aside from the existing wiki documentation and updating the examples, I'm open to it.

**Comment by commonsensesoftware** [comment]
I believe this issue has been resolved and driven to conclusion. If there is anything more, feel free to comment or reopen the issue as appropriate.
