### ISSUE TITLE
AmbiguousActionException when upgrading from Microsoft.AspNetCore.Mvc.Versioning 5.0.0 to Asp.Versioning.Mvc 7.0.0

### ISSUE THREAD

**Issue by alexrosenfeld10** [dotnet/aspnet-api-versioning#969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've recently upgraded from net5.0 to net7.0 and I'm getting this error:

Error processing request
Microsoft.AspNetCore.Mvc.Infrastructure.AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied:

Here is what my controller looks like:

```csharp
using Asp.Versioning;
using Microsoft.AspNetCore.Mvc;

namespace My.App.Controllers;

[ApiVersion("1.0")]
[ApiVersion("2.0")]
[ApiController]
[Route("api/v{version:apiVersion}/debug/{id}")]
public class DebugController : ControllerBase
{
    [HttpGet]
    [MapToApiVersion("1.0")]
    public IActionResult Start([FromRoute] string id)
    {
        return Ok(id);
    }

    [HttpGet]
    [MapToApiVersion("2.0")]
    public IActionResult Start([FromRoute] string id, [FromQuery] string foo)
    {
        return Ok(id);
    }
}

```

If I upgrade to `net7` but leave the versioning package at 5.0.0 things remain working.

I call 
```csharp
        builder.Services
            .AddApiVersioning()
            .AddApiExplorer(options => options.GroupNameFormat = "'v'VVV")
            .AddMvc();
```

on startup.

### Expected Behavior

Things work the way they did before

### .NET Version

7.0.102

### Anything else?

I realize this isn't very reproducible. I'm not sure what's going on here, I've cloned down the example projects and they work as expected. If you have any insight here I'd appreciate it. Thanks to anyone who can help

**Comment by alexrosenfeld10** [comment]
Closing this. Sorry for the noise. For anyone else looking, it's because I was calling
```csharp
var app = builder.Build();
app.UseMvc();
```

**Comment by alexrosenfeld10** [comment]
@commonsensesoftware What if I want controller support, but not MVC? As in, just `MapControllers()` level?

**Comment by alexrosenfeld10** [comment]
It seems like that's not supported?

**Comment by commonsensesoftware** [comment]
As mentioned above, `IApiVersioningBuiler.AddMvc` == **MVC (Core)** and not the full MVC UI stack. In hindsight, I guess I should have called it `MvcCore`. I thought it would be really obvious that `AddMvc` only means _core_ without being overly verbose. Who would try to version UI controllers? (yes - technically - those people are out there 😆). A lot people have gotten hung up the name `AddMvc`.

API Versioning does not, and never will, directly use, require, or demonstrate applying versioning to UI controllers. Those ambitious enough to configure it, go right ahead. When people ask, I will answer their questions, but it's not something I ever plan to highlight. 😄

**Comment by alexrosenfeld10** [comment]
Gotcha. Yep, that's not what I'm trying to do. Thanks for clarifying all this!
