### ISSUE TITLE
Add ControllerNameAttribute

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnet-api-versioning#970]
I had the same [issue ](https://github.com/dotnet/aspnetcore/issues/31026#issue-834927901)with people thinking it was from. Net team, can the.Net team add a ControllerNameAttribute to match the placeholder in the routing template

**Comment by javiercn** [comment]
@Varorbc We move issues as we think appropriate as per our triage processes. 

If you are asking for the feature to be part of ASP.NET Core, this is not a priority for us and not something we plan to add in the short term.
