### ISSUE TITLE
MethodNotAllowed when using {catchall} in YARP

### ISSUE THREAD

**Issue by Sebberrou** [dotnet/aspnet-api-versioning#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am not sure if my bug is related to this issue : #930

We upgraded our services to .net 7 and migrated from Microsoft.AspNetCore.Mvc.Versioning to Asp.Versionning.
When using Yarp using a catch-all we want to be able to override some specific routes. But when using asp.versioning the routes with different method but the same path will start responding `405 MethodNotAllowed` instead of going to YARP.

### Expected Behavior

a 405 MethodNotAllowed result should not be return when a catch-all exist in YARP

### Steps To Reproduce

I have a small repo replicating the problem here : https://gitlab.com/SebBerrou/yarp-api-versioning

We are using a global {**catch-all} to our services in yarp
```json
"Routes": {
 "serviceA": {
        "ClusterId": "serviceA",
        "Order": 99,
        "Match": {
          "Path": "/api/serviceA/{**catch-all}"
        },
        "Transforms": [
          { "RequestHeadersCopy": "true" }
        ]
      },
}
"Clusters": {
        "serviceA": {
          "Destinations": {
            "destination1": {
              "Address": "http://serviceA.api"
            }
          }
        }
}
```
And we want to override some routes in a controller in the project
```csharp
[ApiVersion(1.0)]
[ApiController]
[Route("/api/serviceA")]
public class ServiceAController : ControllerBase
{
    [HttpPost(Name = "PostServiceA")]
    public string Post()
    {
        // Custom routing
        return "Post service A";
    }
}
```

But when we add the versioning, YARP can not forward calls to `GET /api/serviceA` we get a 405 MethodNotAllowed result.
Call to sub routes are routed as expected, for example `GET /api/serviceA/test`. 

Also if I add catch-all route without YARP it works fine.
```csharp
    [Route("{**catch-all}", Name = "CatchAllServiceA")]
    public string CatchAll()
    {
        return "Catch all service A";
    }
```

### .NET Version

.net 7.0

**Comment by Sebberrou** [comment]
Finally understood and found a fix. 
Asp.Versioning needed to correctly know about the YARP routes. I fixed my problem by changing the way I register YARP in my Program.cs. Could this be worth documenting?
`app.NewVersionedApi().HasApiVersion(1.0).MapReverseProxy()`

**Comment by commonsensesoftware** [comment]
This looks related to #930. I see you've linked to a repro so I will definitely take a peek and work from that. Discovery and splitting across implementations is intended to be supported, but there hasn't been a specific way to do until now. YARP is a great use case and I would like there to be frictionless support.
