### ISSUE TITLE
Issue during retrieving Versions with DescribeApiVersions when one of the version is deprecated

### ISSUE THREAD

**Issue by Krohitkrishna12** [dotnet/aspnet-api-versioning#995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting exception retrieving versions using the DescribeApiVersions method used during building the swagger endpoint for each version, when one of the version is marked deprecated with a specific setup of controller classes described in the Steps to reproduce section its throwing exception.

### Expected Behavior

To return Versions

### Failing Setup
```
[ApiVersion(2.0)]
[Route("api/v{version:apiVersion}/[controller]")] //Helps the Url segment versioning
[Route("api/[controller]")] //Helps the Header & Media Type Versioning
public class V2ApiController : BaseApiController
{
}

[ApiVersion(1.0, Deprecated=true)]
[Route("api/v{version:apiVersion}/[controller]")] //Helps the Url segment versioning
[Route("api/[controller]")] //Helps the Header & Media Type Versioning
public class V1ApiController : BaseApiController
{
}


[ApiController]
public class BaseApiController : ControllerBase
{
}

namespace Application.Features.V2.Feature1;

public class Feature1Controller : V2ApiController
{
   /// <summary>
   /// Get a List of Random Numbers From V2
   /// </summary>
   /// <returns></returns>
   ///<response code="200">Returns List</response>
   [HttpGet()]
   [ProducesResponseType(StatusCodes.Status200OK)]
   // [Route("V2Nums")]
   public async Task<ActionResult<List<int>>> Get()
   {
      // throw new CustomException("My Exception with no details");
      return await Task.Run(() =>
          Enumerable.Range(1, 10)
              .Select(i => new Random().Next())
              .ToList());
   }
}

namespace Application.Features.V1.Feature1;

public class Feature1Controller : V1ApiController
{
   private Random _random;

   public Feature1Controller()
   {
      _random = new Random();
   }

   /// <summary>
   /// Get a List of Random Numbers
   /// </summary>
   /// <returns></returns>
   ///<response code="200">Returns List</response>
   [HttpGet()]
   [ProducesResponseType(StatusCodes.Status200OK)]
// [Route("V1Nums")]
   public async Task<ActionResult<List<int>>> Get()
   {
      // throw new CustomException("My Exception with no details");
      return await Task.Run(() =>
          Enumerable.Range(1, 10)
              .Select(i => _random.Next())
              .ToList());
   }
}

foreach (ApiVersionDescription description in ((WebApplication)app).DescribeApiVersions().Reverse())
{
   string isDeprecated = description.IsDeprecated ? " (DEPRECATED)" : string.Empty;
   var url = $"/swagger/{description.GroupName}/swagger.json";
   var name = $"{description.GroupName.ToUpperInvariant()}{isDeprecated}";
   options.SwaggerEndpoint(url, name);
}
```

### Working Setup
```

namespace Application.Features.V2.Feature1;

 [ApiController]
 [ApiVersion(2.0)]
 [Route("api/v{version:apiVersion}/[controller]")] //Helps the Url segment versioning
[Route("api/[controller]")]
public class Feature1Controller : ControllerBase
{
   /// <summary>
   /// Get a List of Random Numbers From V2
   /// </summary>
   /// <returns></returns>
   ///<response code="200">Returns List</response>
   [HttpGet()]
   [ProducesResponseType(StatusCodes.Status200OK)]
   public async Task<ActionResult<List<int>>> Get()
   {
      // throw new CustomException("My Exception with no details");
      return await Task.Run(() =>
          Enumerable.Range(1, 10)
              .Select(i => new Random().Next())
              .ToList());
   }
}

namespace Application.Features.V1.Feature1;

[ApiController]
[ApiVersion(1.0, Deprecated = true)]
[Route("api/v{version:apiVersion}/[controller]")] //Helps the Url segment versioning
[Route("api/[controller]")]
public class Feature1Controller : ControllerBase
{
   private Random _random;

   public Feature1Controller()
   {
      _random = new Random();
   }

   /// <summary>
   /// Get a List of Random Numbers
   /// </summary>
   /// <returns></returns>
   ///<response code="200">Returns List</response>
   [HttpGet()]
   [ProducesResponseType(StatusCodes.Status200OK)]
   public async Task<ActionResult<List<int>>> Get()
   {
      // throw new CustomException("My Exception with no details");
      return await Task.Run(() =>
          Enumerable.Range(1, 10)
              .Select(i => _random.Next())
              .ToList());
   }
}
```

### Exceptions (if any)

```
Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in Microsoft.AspNetCore.Mvc.Core.dll but was not handled in user code: 'Action 'Application.Features.V2.Feature1.Feature1Controller.Get (Application)' does not have an attribute route. Action methods on controllers annotated with ApiControllerAttribute must be attribute routed.'
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ApiBehaviorApplicationModelProvider.EnsureActionIsAttributeRouted(ActionModel actionModel)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ApiBehaviorApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelFactory.CreateApplicationModel(IEnumerable`1 controllerTypes)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Asp.Versioning.ApiExplorer.ActionApiVersionMetadataCollationProvider.get_Version()
   at Asp.Versioning.ApiExplorer.DefaultApiVersionDescriptionProvider.ApiVersionDescriptionCollection.ComputeVersion(IApiVersionMetadataCollationProvider[] providers)
   at Asp.Versioning.ApiExplorer.DefaultApiVersionDescriptionProvider.ApiVersionDescriptionCollection.ComputeVersion()
   at Asp.Versioning.ApiExplorer.DefaultApiVersionDescriptionProvider.ApiVersionDescriptionCollection.get_Items()
   at Asp.Versioning.ApiExplorer.DefaultApiVersionDescriptionProvider.get_ApiVersionDescriptions()
   at Microsoft.AspNetCore.Builder.IEndpointRouteBuilderExtensions.DescribeApiVersions(IEndpointRouteBuilder endpoints)
   at BuildingBlocks.Documentation.Startup.<>c__DisplayClass0_0.<UseSwaggerDocumentation>b__0(SwaggerUIOptions options) 
```

### .NET Version

7.0.302

### Anything else?

Runing in VSCode on Linux in chromebook.

Is the failing setup not a valid setup for controllers with versioning? Another interesting thing is if i include attribute routes to the actions the versions are completely ignored in failing setup and in Swagger i only see V2 with both actions showing up.

![image](https://github.com/dotnet/aspnet-api-versioning/assets/134893525/3e4ab512-ce22-418c-9bbe-11e1bb2e17e2)
![Untitled](https://github.com/dotnet/aspnet-api-versioning/assets/134893525/14f51937-202a-4aaa-84ce-d3d9693d707f)

**Comment by commonsensesoftware** [comment]
I was able to repro the condition from your input, but not that specific exception. It makes me think it may have been observed between various changes you were trying. The API Explorer only support attribute routing.

You should have received an exception indicating duplicate routes for `api/v1/feature1` and `api/feature1`. This happens because you are using inheritance. `ApiVersionAttribute` and its sibling attributes are **not** inherited. This is by design. If the attributes were inherited, it would be very easy to get in a situation where values overlap and become ambiguous. You did not do that; however, the following would cause the behavior:

```c#
namespace My.Api.V1
{
    [ApiVersion(1.0}]
    [ApiController]
    [Route("[controller]")]
    public class FeatureController : ControllerBase
    {
        [HttpGet]
        public virtual IActionResult Get() => Ok();
    }
}

namespace My.Api.V2
{
    [ApiVersion(2.0}] // oops! this controller has 1.0 and 2.0 due to inheritance
    public class FeatureController : V1.FeatureController
    {
        [HttpGet]
        public override IActionResult Get() => Ok();
    }
}
```

Since the `2.0` controller inherits the `1.0` it will support both `1.0` and `2.0`. That means there are two different controllers with the same route template and API version, which is ambiguous. There is a configuration where this is not the case, but this is an ease landmine to step on and the error message is not obvious.

There are several solutions to this behavior:

1. Don't use inheritance (personally, I think it's the wrong abstraction and extension methods or results are a better alternative)
2. Decorate the appropriate controllers with the correct `[ApiVersion]`
   a. If you don't want to apply the version to every controller, you can use a convention; for example, you can use the `VersionByNamespace` convention
3. Use you own custom attributes by extending `ApiVersionsBaseAttribute` or roll attributes from scratch that implement `IApiVersionProvider`.

Ultimately, API Versioning doesn't care about specific attributes. It only cares about `IApiVersionProvider` and provides a few out-of-the-box attributes that implement it. `#3` gives you full control to implement attributes however you like, including with support for inheritance.

**Comment by Krohitkrishna12** [comment]
one more question i got while reading your reply is :

"You should have received an exception indicating duplicate routes for api/v1/feature1 and api/feature1". 

So are you saying the below 2 routes should not be used in conjunction to allow for URL segment versioning and Header Versioning? Because without the  2 Header versioning doesnt work in the test api im trying.
1. [Route("api/v{version:apiVersion}/[controller]")] //Helps the Url segment versioning
2. [Route("api/[controller]")] //Helps the Header & Media Type Versioning

**Comment by commonsensesoftware** [comment]
No. You can have multiple route registration like that - if you want to.

I took your _non-working_ controller setup as is. It produced this exception:

```console
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Conflicting method/path combination "GET api/v1/Feature" for actions - Application.Features.V1.Feature1.Feature1Controller.Get (OpenApiExample),Application.Features.V2.Feature1.Feature1Controller.Get (OpenApiExample). Actions require a unique method/path combination for Swagger/OpenAPI 3.0. Use ConflictingActionsResolver as a workaround
  at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
  at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
  at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
  at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
  at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
  at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

This makes sense to me because neither `Application.Features.V2.Feature1.Feature1Controller` nor `Application.Features.V1.Feature1.Feature1Controller` has any direct attribution. You cannot have an _unversioned_ API, which means both of these controllers will use the value `ApiVersioningOptions.DefaultApiVersion`, which defaults to `1.0`. Since they do inherit the same route templates, the two routes are now ambiguous.

I hope that clears things up.

**Comment by Krohitkrishna12** [comment]
Ah since the attributes are not inherited essentially the default values are kicking in which makes the route ambiguous. Thank you for pointing that out. Cleared things up now. Thanks for the patience. Appreciate it. 👍  💯

**Comment by commonsensesoftware** [comment]
It would appear that the answers to your questions resolved the issue. It seems you got things working. If that's not the case, feel free to ask more questions and/or re-open the issue.
